force-app/main/default/objects/Mst_Makers__c/Mst_Makers__c.object-meta.xml
<CustomObject>
    <label>メーカ</label>
    <nameField>
        <label>メーカ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mst_Makers__c/fields/disp_flg__c.field-meta.xml
<CustomField>
    <fullName>disp_flg__c</fullName>
    <defaultValue>&quot;1&quot;</defaultValue>
    <label>表示区分</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>disp_flg</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mst_Makers__c/fields/inum__c.field-meta.xml
<CustomField>
    <fullName>inum__c</fullName>
    <externalId>true</externalId>
    <label>INUM</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mst_Makers__c/fields/row_num__c.field-meta.xml
<CustomField>
    <fullName>row_num__c</fullName>
    <label>表示順</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/MakerDao.cls
/*
 * メーカーDao
 */
public without sharing class MakerDao {

    // コンストラクタ
    public MakerDao() {
    }

    public List<Mst_Makers__c> getAllMaker(){
        return [
            SELECT
                Id
                ,Name
                ,inum__c
            FROM
                Mst_Makers__c
            WHERE
                Name <> '--'
            AND
                disp_flg__c='1'
            ORDER BY
                row_num__c
        ];
    }
}