force-app/main/default/objects/Mst_Makers__c/Mst_Makers__c.object-meta.xml
<CustomObject>
    <label>メーカ</label>
    <nameField>
        <label>メーカ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mst_Makers__c/fields/disp_flg__c.field-meta.xml
<CustomField>
    <fullName>disp_flg__c</fullName>
    <defaultValue>&quot;1&quot;</defaultValue>
    <label>表示区分</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>disp_flg</valueSetName>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mst_Makers__c/fields/inum__c.field-meta.xml
<CustomField>
    <fullName>inum__c</fullName>
    <externalId>true</externalId>
    <label>INUM</label>
    <length>11</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mst_Makers__c/fields/maker__c.field-meta.xml
<CustomField>
    <fullName>maker__c</fullName>
    <externalId>true</externalId>
    <label>メーカー（数字）</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mst_Makers__c/fields/row_num__c.field-meta.xml
<CustomField>
    <fullName>row_num__c</fullName>
    <label>表示順</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Mst_Models__c/Mst_Models__c.object-meta.xml
<CustomObject>
    <label>車種</label>
    <nameField>
        <label>車種名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mst_Models__c/fields/inum__c.field-meta.xml
<CustomField>
    <fullName>inum__c</fullName>
    <externalId>true</externalId>
    <label>INUM</label>
    <length>11</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Mst_Models__c/fields/maker__c.field-meta.xml
<CustomField>
    <fullName>maker__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>メーカ</label>
    <referenceTo>Mst_Makers__c</referenceTo>
    <relationshipLabel>車種</relationshipLabel>
    <relationshipName>models</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Mst_Models__c/fields/row_num__c.field-meta.xml
<CustomField>
    <fullName>row_num__c</fullName>
    <label>並び替え用</label>
    <precision>8</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ModelDao.cls
/*
 * 車種Dao
 */
public with sharing class ModelDao {

    // コンストラクタ
    public ModelDao() {
    }

    public List<Mst_Models__c> getSelectModel(List<String> makerList){
        return [
            SELECT
                Id
                ,Name
                ,inum__c
                ,disp_flg__c
                ,maker__c
                ,maker__r.Name 
                ,maker__r.inum__c
            FROM
                Mst_Models__c
            WHERE maker__r.inum__c IN :makerList
            AND disp_flg__c='1'
            ORDER BY
                row_num__c
            Limit 50000
        ];
    }

}