force-app/main/default/objects/ModelYear__c/ModelYear__c.object-meta.xml
<CustomObject>
    <label>年式マスタ</label>
    <nameField>
        <label>年式マスタ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchaseOpportunity__c/PurchaseOpportunity__c.object-meta.xml
<CustomObject>
    <label>買取商談</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>買取商談No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchaseOpportunity__c/fields/CorporationID__c.field-meta.xml
<CustomField>
    <fullName>CorporationID__c</fullName>
    <description>法人管理システムと連携するための連携項目、入力されているのはロット番号</description>
    <externalId>true</externalId>
    <inlineHelpText>法人のみ使用。基幹から読み込むためのＩＤ。</inlineHelpText>
    <label>法人ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PurchaseOpportunity__c/fields/ModelYear__c.field-meta.xml
<CustomField>
    <fullName>ModelYear__c</fullName>
    <description>現在使用していない</description>
    <inlineHelpText>西暦で入力する</inlineHelpText>
    <label>年式(テキスト)</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunity__c/fields/ModelYearPickList__c.field-meta.xml
<CustomField>
    <fullName>ModelYearPickList__c</fullName>
    <label>年式</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>2026</fullName>
                <label>2026年/令和8年</label>
            </value>
            <value>
                <fullName>2025</fullName>
                <label>2025年/令和7年</label>
            </value>
            <value>
                <fullName>2024</fullName>
                <label>2024年/令和6年</label>
            </value>
            <value>
                <fullName>2023</fullName>
                <label>2023年/令和5年</label>
            </value>
            <value>
                <fullName>2022</fullName>
                <label>2022年/令和4年</label>
            </value>
            <value>
                <fullName>2021</fullName>
                <label>2021年/令和3年</label>
            </value>
            <value>
                <fullName>2020</fullName>
                <label>2020年/令和2年</label>
            </value>
            <value>
                <fullName>2019</fullName>
                <label>2019年/平成31年（令和元年）</label>
            </value>
            <value>
                <fullName>2018</fullName>
                <label>2018年/平成30年</label>
            </value>
            <value>
                <fullName>2017</fullName>
                <label>2017年/平成29年</label>
            </value>
            <value>
                <fullName>2016</fullName>
                <label>2016年/平成28年</label>
            </value>
            <value>
                <fullName>2015</fullName>
                <label>2015年/平成27年</label>
            </value>
            <value>
                <fullName>2014</fullName>
                <label>2014年/平成26年</label>
            </value>
            <value>
                <fullName>2013</fullName>
                <label>2013年/平成25年</label>
            </value>
            <value>
                <fullName>2012</fullName>
                <label>2012年/平成24年</label>
            </value>
            <value>
                <fullName>2011</fullName>
                <label>2011年/平成23年</label>
            </value>
            <value>
                <fullName>2010</fullName>
                <label>2010年/平成22年</label>
            </value>
            <value>
                <fullName>2009</fullName>
                <label>2009年/平成21年</label>
            </value>
            <value>
                <fullName>2008</fullName>
                <label>2008年/平成20年</label>
            </value>
            <value>
                <fullName>2007</fullName>
                <label>2007年/平成19年</label>
            </value>
            <value>
                <fullName>2006</fullName>
                <label>2006年/平成18年</label>
            </value>
            <value>
                <fullName>2005</fullName>
                <label>2005年/平成17年</label>
            </value>
            <value>
                <fullName>2004</fullName>
                <label>2004年/平成16年</label>
            </value>
            <value>
                <fullName>2003</fullName>
                <label>2003年/平成15年</label>
            </value>
            <value>
                <fullName>2002</fullName>
                <label>2002年/平成14年</label>
            </value>
            <value>
                <fullName>2001</fullName>
                <label>2001年/平成13年</label>
            </value>
            <value>
                <fullName>2000</fullName>
                <label>2000年/平成12年</label>
            </value>
            <value>
                <fullName>1999</fullName>
                <label>1999年/平成11年</label>
            </value>
            <value>
                <fullName>1998</fullName>
                <label>1998年/平成10年</label>
            </value>
            <value>
                <fullName>1997</fullName>
                <label>1997年/平成9年</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PurchaseOpportunityWork__c/PurchaseOpportunityWork__c.object-meta.xml
<CustomObject>
    <label>買取商談（ワーク）</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>買取商談（ワーク）No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchaseOpportunityWork__c/fields/CorporationID__c.field-meta.xml
<CustomField>
    <fullName>CorporationID__c</fullName>
    <externalId>true</externalId>
    <label>法人ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunityWork__c/fields/ModelYear__c.field-meta.xml
<CustomField>
    <fullName>ModelYear__c</fullName>
    <label>年式</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/NXI_POpportunityWorkTriggerHandler.cls
public class NXI_POpportunityWorkTriggerHandler {
	private Boolean m_isExecuting = false;
    private Integer batchSize = 0;

    public NXI_POpportunityWorkTriggerHandler(Boolean isExecuting, Integer size){
        m_isExecuting = isExecuting;
        batchSize = size;
    }

    public void OnBeforeInsert(List<PurchaseOpportunityWork__c> newPOpportunityWorks){
    }  
    public void OnAfterInsert(List<PurchaseOpportunityWork__c> newPOpportunityWorks){
        createPOpportunities(newPOpportunityWorks);
    }
    public void OnBeforeUpdate(List<PurchaseOpportunityWork__c> oldPOpportunityWorks, Map<Id, PurchaseOpportunityWork__c> oldPOpportunityWorkMap, List<PurchaseOpportunityWork__c> newPOpportunityWorks, Map<Id, PurchaseOpportunityWork__c> newPOpportunityWorkMap){
    }
    public void OnAfterUpdate(List<PurchaseOpportunityWork__c> oldPOpportunityWorks, Map<Id, PurchaseOpportunityWork__c> oldPOpportunityWorkMap, List<PurchaseOpportunityWork__c> newPOpportunityWorks, Map<Id, PurchaseOpportunityWork__c> newPOpportunityWorkMap){
    }
    public void OnBeforeDelete(List<PurchaseOpportunityWork__c> pOpportunityWorksToDelete, Map<Id, PurchaseOpportunityWork__c> oldPOpportunityWorkMap){
    }
    public void OnAfterDelete(List<PurchaseOpportunityWork__c> oldPOpportunityWorks, Map<Id, PurchaseOpportunityWork__c> oldPOpportunityWorkMap){
    }
    public void OnUndelete(List<PurchaseOpportunityWork__c> newPOpportunityWorks){
    }
    
    public void createPOpportunities(List<PurchaseOpportunityWork__c> pOpportunityWorks) {
        List<User> users = new List<User>();
        users = NXI_Dao.getUsers();
        
        Map<String, User> userMapByUserCode = new Map<String, User>();
        for (User user : users) {
            if (String.isBlank(user.UserCode__c)) {
                continue;
            }
            userMapByUserCode.put(user.UserCode__c, user);
        }
        
        Set<String> powCustomFieldAPINameSet = new Set<String>();
        powCustomFieldAPINameSet = NXI_Util.getCustomFieldAPINameSet(PurchaseOpportunityWork__c.sObjectType);
        
        Set<String> poCustomFieldAPINameSet = new Set<String>();
        poCustomFieldAPINameSet = NXI_Util.getCustomFieldAPINameSet(PurchaseOpportunity__c.sObjectType);
        
        List<PurchaseOpportunityWork__c> targetPurchaseOpportunityWorks = new List<PurchaseOpportunityWork__c>();
        targetPurchaseOpportunityWorks = NXI_Dao.getPurchaseOpportunityWorks(pOpportunityWorks);
        
        List<PurchaseOpportunity__c> purchaseOpportunities_ups = new List<PurchaseOpportunity__c>();
        
        for (PurchaseOpportunityWork__c targetPurchaseOpportunityWork : targetPurchaseOpportunityWorks) {
            PurchaseOpportunity__c purchaseOpportunity_ups = new PurchaseOpportunity__c();
            
            //特殊処理
            //所有者コード→所有者変換
            if (userMapByUserCode.containsKey(targetPurchaseOpportunityWork.UserCode__c)) {
                purchaseOpportunity_ups.OwnerId = userMapByUserCode.get(targetPurchaseOpportunityWork.UserCode__c).Id;
            }
            
            for (String customFieldAPIName : powCustomFieldAPINameSet) {
                if (!poCustomFieldAPINameSet.contains(customFieldAPIName)) {
                    continue;
                }
                if (customFieldAPIName == 'UserCode__c') {
                    continue;
                }
                if(customFieldAPIName =='ModelYear__c'){
                  purchaseOpportunity_ups.put('ModelYearPickList__c',    targetPurchaseOpportunityWork.get(customFieldAPIName));
                }
                purchaseOpportunity_ups.put(customFieldAPIName, targetPurchaseOpportunityWork.get(customFieldAPIName));
            }
            
            purchaseOpportunities_ups.add(purchaseOpportunity_ups);
        }
        
        if (!purchaseOpportunities_ups.isEmpty()) {
            upsert purchaseOpportunities_ups CorporationID__c;
        }
        
        if (!targetPurchaseOpportunityWorks.isEmpty()) {
            delete targetPurchaseOpportunityWorks;
            Database.emptyRecycleBin(targetPurchaseOpportunityWorks);
        }
    }
}