force-app/main/default/objects/Case__c/Case__c.object-meta.xml
<CustomObject>
    <label>買取受付</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>買取受付No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>お名前　★</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>買取受付</relationshipLabel>
    <relationshipName>AccountCase</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PurchaseExperienceWork__c/PurchaseExperienceWork__c.object-meta.xml
<CustomObject>
    <label>買取実績（ワーク）</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>買取実績（ワーク）No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchaseOpportunityWork__c/PurchaseOpportunityWork__c.object-meta.xml
<CustomObject>
    <label>買取商談（ワーク）</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>買取商談（ワーク）No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchaseOpportunityWork__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>買取商談（ワーク）</relationshipLabel>
    <relationshipName>AccountOpportunityWork</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WorkExchange__c/WorkExchange__c.object-meta.xml
<CustomObject>
    <label>連携用オブジェクト</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NXI_DaoTest.cls
@isTest
public class NXI_DaoTest {
    @isTest
    public static void test01() {
        List<User> users = NXI_Dao.getUsers();
        Account ac = new Account(LastName = 'nakamura');
        insert ac;
       // Case__c cc = new Case__c(Account__c=ac.id );
        
        List<Id> idlist = new List<Id>();
        
        List<Case__c> cclist =  NXI_Dao.getCustomCase(idlist);
        List<WorkExchange__c>  welist =NXI_Dao.getWorkExchange(idlist);
        
        String  results = NXI_Dao.getLastAssessmentDateByAccount();
       
        List<PurchaseOpportunityWork__c> woplist = new List<PurchaseOpportunityWork__c>();
        List<PurchaseOpportunityWork__c> selectlist   =  NXI_Dao.getPurchaseOpportunityWorks(woplist);
        
        List<PurchaseExperienceWork__c> weplist = new List<PurchaseExperienceWork__c>();
        List<PurchaseExperienceWork__c> selectlist2   =  NXI_Dao.getPurchaseExperienceWorks(weplist);
        

    }
   

}