force-app/main/default/objects/Mst_Assess_Users__c/Mst_Assess_Users__c.object-meta.xml
<CustomObject>
    <description>査定アプリユーザ管理用オブジェクト（正社員および業者）</description>
    <label>査定ユーザ</label>
    <nameField>
        <label>査定ユーザ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mst_Assess_Users__c/fields/emp_kind__c.field-meta.xml
<CustomField>
    <fullName>emp_kind__c</fullName>
    <label>社員区分</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>営業ユーザ</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>ヤードユーザ</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>取引先</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>提携業者様</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>外部ユーザ</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mst_Assess_Users__c/fields/Invalid__c.field-meta.xml
<CustomField>
    <fullName>Invalid__c</fullName>
    <defaultValue>false</defaultValue>
    <label>無効</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Mst_Assess_Users__c/fields/login_user__c.field-meta.xml
<CustomField>
    <fullName>login_user__c</fullName>
    <externalId>true</externalId>
    <label>ログインID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Mst_Assess_Users__c/fields/manage_org__c.field-meta.xml
<CustomField>
    <fullName>manage_org__c</fullName>
    <label>統括部門</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>札幌支店</fullName>
            </value>
            <value>
                <fullName>盛岡支店</fullName>
            </value>
            <value>
                <fullName>仙台支店</fullName>
            </value>
            <value>
                <fullName>水戸支店</fullName>
            </value>
            <value>
                <fullName>群馬支店</fullName>
            </value>
            <value>
                <fullName>千葉支店</fullName>
            </value>
            <value>
                <fullName>東京支店</fullName>
            </value>
            <value>
                <fullName>埼玉支店</fullName>
            </value>
            <value>
                <fullName>横浜支店</fullName>
            </value>
            <value>
                <fullName>新潟支店</fullName>
            </value>
            <value>
                <fullName>長野支店</fullName>
            </value>
            <value>
                <fullName>岐阜支店</fullName>
            </value>
            <value>
                <fullName>静岡支店</fullName>
            </value>
            <value>
                <fullName>名古屋支店</fullName>
            </value>
            <value>
                <fullName>金沢支店</fullName>
            </value>
            <value>
                <fullName>京都支店</fullName>
            </value>
            <value>
                <fullName>大阪支店</fullName>
            </value>
            <value>
                <fullName>兵庫支店</fullName>
            </value>
            <value>
                <fullName>高松支店</fullName>
            </value>
            <value>
                <fullName>広島支店</fullName>
            </value>
            <value>
                <fullName>鳥取支店</fullName>
            </value>
            <value>
                <fullName>山口</fullName>
            </value>
            <value>
                <fullName>福岡支店</fullName>
            </value>
            <value>
                <fullName>熊本支店</fullName>
            </value>
            <value>
                <fullName>鹿児島支店</fullName>
            </value>
            <value>
                <fullName>沖縄支店</fullName>
            </value>
            <value>
                <fullName>リテール事業部</fullName>
            </value>
            <value>
                <fullName>大阪本社</fullName>
            </value>
            <value>
                <fullName>Cコネクト課</fullName>
            </value>
            <value>
                <fullName>セレクト岸和田</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssessUsersDao.cls
public without sharing class AssessUsersDao {

    // コンストラクタ
    public AssessUsersDao() {
    }

    // 査定担当者（統括部門から取得）
    public List<Mst_Assess_Users__c> getAssessTanto(List<String> manageBumonList){
        return [
            SELECT
                Id
                ,Name
                ,emp_kind__c
                ,manage_org__c
                ,login_user__c
            FROM
                Mst_Assess_Users__c
            WHERE toLabel(manage_org__c) IN :manageBumonList
            // SALESSTRATEGY-4557：無効を検索条件に追加
            AND Invalid__c = False
            ORDER BY
                manage_org__c, Name
        ];

    }

    // SALESSTRATEGY-4557：派生対応 有効な査定ユーザの統括部門を取得
    public List<Mst_Assess_Users__c> getAssessManageOrg(){
        List<Mst_Assess_Users__c> resultList = new List<Mst_Assess_Users__c>();
        Set<String> uniqueOrgSet = new Set<String>();

        // 通常のクエリで取得　※クエリ上でGROUP BY するとエラーになる
        List<Mst_Assess_Users__c> allUsers = [
            SELECT
                Id
                ,Name
                ,manage_org__c
            FROM
                Mst_Assess_Users__c
            WHERE Invalid__c = False
            ORDER BY
                manage_org__c
        ];

        // 重複を排除しながらリストを詰め替える
        for (Mst_Assess_Users__c user : allUsers) {
            if (user.manage_org__c != null && !uniqueOrgSet.contains(user.manage_org__c)) {
                uniqueOrgSet.add(user.manage_org__c);
                resultList.add(user);
            }
        }

        return resultList;
    }
}