force-app/main/default/objects/Mst_Assess_Users__c/Mst_Assess_Users__c.object-meta.xml
<CustomObject>
    <description>査定アプリユーザ管理用オブジェクト（正社員および業者）</description>
    <label>査定ユーザ</label>
    <nameField>
        <label>査定ユーザ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mst_Assess_Users__c/fields/manage_org__c.field-meta.xml
<CustomField>
    <fullName>manage_org__c</fullName>
    <label>統括部門</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>札幌支店</fullName>
            </value>
            <value>
                <fullName>盛岡支店</fullName>
            </value>
            <value>
                <fullName>仙台支店</fullName>
            </value>
            <value>
                <fullName>水戸支店</fullName>
            </value>
            <value>
                <fullName>群馬支店</fullName>
            </value>
            <value>
                <fullName>千葉支店</fullName>
            </value>
            <value>
                <fullName>東京支店</fullName>
            </value>
            <value>
                <fullName>埼玉支店</fullName>
            </value>
            <value>
                <fullName>横浜支店</fullName>
            </value>
            <value>
                <fullName>新潟支店</fullName>
            </value>
            <value>
                <fullName>長野支店</fullName>
            </value>
            <value>
                <fullName>岐阜支店</fullName>
            </value>
            <value>
                <fullName>静岡支店</fullName>
            </value>
            <value>
                <fullName>名古屋支店</fullName>
            </value>
            <value>
                <fullName>金沢支店</fullName>
            </value>
            <value>
                <fullName>京都支店</fullName>
            </value>
            <value>
                <fullName>大阪支店</fullName>
            </value>
            <value>
                <fullName>兵庫支店</fullName>
            </value>
            <value>
                <fullName>高松支店</fullName>
            </value>
            <value>
                <fullName>広島支店</fullName>
            </value>
            <value>
                <fullName>鳥取支店</fullName>
            </value>
            <value>
                <fullName>山口</fullName>
            </value>
            <value>
                <fullName>福岡支店</fullName>
            </value>
            <value>
                <fullName>熊本支店</fullName>
            </value>
            <value>
                <fullName>鹿児島支店</fullName>
            </value>
            <value>
                <fullName>沖縄支店</fullName>
            </value>
            <value>
                <fullName>リテール事業部</fullName>
            </value>
            <value>
                <fullName>大阪本社</fullName>
            </value>
            <value>
                <fullName>Cコネクト課</fullName>
            </value>
            <value>
                <fullName>セレクト岸和田</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mst_Makers__c/Mst_Makers__c.object-meta.xml
<CustomObject>
    <label>メーカ</label>
    <nameField>
        <label>メーカ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mst_Models__c/Mst_Models__c.object-meta.xml
<CustomObject>
    <label>車種</label>
    <nameField>
        <label>車種名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/AssetConstants.cls
/*
 * 定数定義クラス
 */
public with sharing class AssetConstants {

    // オブジェクト名
    public static final String MAKER = 'Mst_Makers__c';     // メーカー
    public static final String MODEL = 'Mst_Models__c';     // 車種
    public static final String ASSESS_TANTO = 'Mst_Assess_Users__c';     // 査定ユーザ

    // 項目名
    public static final String MANAGE_BUMON = 'manage_org__c';     // 統括部門

    // クラス名
    public static final String AUCTION_SEND_SCHEDULE_CLASS = 'AssessmentGetBatchScheduleCon';     // ヤード査定表自動送信バッチスケジュールクラス
    


    // ガバナ回避定義
    // 検索結果の件数
    public static final Integer MAX_SEARCH_DATA_LIMIT = 2000;

    // メッセージ定義
    public static final String MSG_SYSTEM_ERROR = 'システムエラーが発生しました。<br/>検索結果が５万件を超えている可能性があります。<br/>検索条件を絞って再度検索を実行してください。<br/>それでもエラーとなる場合はシステム管理者にご連絡ください。<br/>エラーメッセージ： {0}';
    public static final String MSG_MAX_DATA_LIMIT_ERROR = '検索結果が' + String.valueOf(MAX_SEARCH_DATA_LIMIT) + '件を超えています。<br/>検索条件を増やして対象データを絞り込んでください。';
    public static final String MSG_REQUIRED_ERROR = '*マークが付いた条件を1つ以上設定して下さい。';
    public static final String MSG_AUCTION_ERROR = 'ヤード査定表をオークションサイトへ自動送信する処理でエラーが発生しました。\nsalesforceおよびオークションサイトをご確認ください。\n以下が自動送信できなかった査定表です。\n';
    public static final String MSG_EXCEPTION_ERROR = 'ヤード査定表をオークションサイトへ自動送信するAPI処理で例外処理が発生しました。\n';
    public static final String MSG_AUCTION_SENDBATCH_EXCEPTION_SUBJECT = 'ヤード査定表の自動送信処理で例外が発生しました';
    public static final String MSG_AUCTION_SENDBATCH_EXCEPTION_DISPLAYNAME = 'ヤード査定表自動送信例外処理';
    public static final String MSG_AUCTION_SENDBATCH_ERROR_SUBJECT = 'ヤード査定表の自動送信処理でエラーが発生しました';
    public static final String MSG_AUCTION_SENDBATCH_ERROR_DISPLAYNAME = 'ヤード査定表自動送信エラー処理';

    // 曜日（英語⇒日本語）
    public static final Map<String, String> DAY_OF_THE_WEEK = new Map<String, String>{
        'Sun' => '日'
        , 'Mon' => '月'
        , 'Tue' => '火'
        , 'Wed' => '水'
        , 'Thu' => '木'
        , 'Fri' => '金'
        , 'Sat' => '土'
    };

    // タイムゾーン
    public static final String TIMEZONE = 'Asia/Tokyo';
}