force-app/main/default/objects/PurchaseOpportunity__c/PurchaseOpportunity__c.object-meta.xml
<CustomObject>
    <label>買取商談</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>買取商談No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchaseOpportunity__c/fields/AssessmentDate__c.field-meta.xml
<CustomField>
    <fullName>AssessmentDate__c</fullName>
    <inlineHelpText>未入力でフェーズが保留の時、当日が自動的にセットされます。</inlineHelpText>
    <label>査定日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunity__c/fields/CancelDate__c.field-meta.xml
<CustomField>
    <fullName>CancelDate__c</fullName>
    <description>フェーズをキャンセルにしたら自動でその日付が入力される</description>
    <inlineHelpText>未入力でフェーズがキャンセルの時、当日が自動的にセットされます。</inlineHelpText>
    <label>キャンセル日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunity__c/fields/CarryDate__c.field-meta.xml
<CustomField>
    <fullName>CarryDate__c</fullName>
    <inlineHelpText>未入力の時、引取日が自動的にセットされます。</inlineHelpText>
    <label>搬入日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunity__c/fields/CompletionDate__c.field-meta.xml
<CustomField>
    <fullName>CompletionDate__c</fullName>
    <inlineHelpText>未入力でフェーズが全完了の時、当日が自動的にセットされます。</inlineHelpText>
    <label>全完了日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunity__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <description>買取商談のフェーズのパスの元になっている項目</description>
    <inlineHelpText>【受付】TEL・FAX等の査定依頼が来た状態。（依頼査定の場合は必ず入力）【保留】査定済み、商談中。未成約状態。（現地で見つけた査定はココからスタート）【買取】成約済み。引取・出品・支払い等進行中【全完了】引取。出品・支払い・後処理等全ての処理が完了【キャンセル】買取できず。</inlineHelpText>
    <label>フェーズ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>受付</fullName>
                <default>true</default>
                <label>受付</label>
            </value>
            <value>
                <fullName>保留</fullName>
            </value>
            <value>
                <fullName>買取</fullName>
            </value>
            <value>
                <fullName>全完了</fullName>
            </value>
            <value>
                <fullName>キャンセル</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PurchaseOpportunity__c/fields/PurchaseDate__c.field-meta.xml
<CustomField>
    <fullName>PurchaseDate__c</fullName>
    <inlineHelpText>未入力でフェーズが買取の時、当日が自動的にセットされます。</inlineHelpText>
    <label>買取日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunity__c/fields/RequestDate__c.field-meta.xml
<CustomField>
    <fullName>RequestDate__c</fullName>
    <inlineHelpText>依頼がない場合は入力しないでください。
未入力でフェーズが受付の時、当日が自動的にセットされます。</inlineHelpText>
    <label>査定依頼日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunity__c/fields/TakeUpDate__c.field-meta.xml
<CustomField>
    <fullName>TakeUpDate__c</fullName>
    <label>引取日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/NXI_POpportunityTriggerHandler.cls
public class NXI_POpportunityTriggerHandler {

    private Boolean m_isExecuting = false;
    private Integer batchSize = 0;

    public NXI_POpportunityTriggerHandler(Boolean isExecuting, Integer size){
        m_isExecuting = isExecuting;
        batchSize = size;
    }
    public void OnBeforeInsert(List<PurchaseOpportunity__c> newPOpportunitys){
		autoSetPurchaseOpportunity(newPOpportunitys);
    }  
    public void OnAfterInsert(List<PurchaseOpportunity__c> newPOpportunitys){
    }
    public void OnBeforeUpdate(List<PurchaseOpportunity__c> oldPOpportunitys, Map<Id, PurchaseOpportunity__c> oldPOpportunityMap, List<PurchaseOpportunity__c> newPOpportunitys, Map<Id, PurchaseOpportunity__c> newPOpportunityMap){
		autoSetPurchaseOpportunity(newPOpportunitys);
    }
    public void OnAfterUpdate(List<PurchaseOpportunity__c> oldPOpportunitys, Map<Id, PurchaseOpportunity__c> oldPOpportunityMap, List<PurchaseOpportunity__c> newPOpportunitys, Map<Id, PurchaseOpportunity__c> newPOpportunityMap){
    }
    public void OnBeforeDelete(List<PurchaseOpportunity__c> pOpportunitysToDelete, Map<Id, PurchaseOpportunity__c> oldPOpportunityMap){
    }
    public void OnAfterDelete(List<PurchaseOpportunity__c> oldPOpportunitys, Map<Id, PurchaseOpportunity__c> oldPOpportunityMap){
    }
    public void OnUndelete(List<PurchaseOpportunity__c> newPOpportunitys){
    } 

    public void autoSetPurchaseOpportunity(List<PurchaseOpportunity__c> pOpportunitys) {
        
        for (PurchaseOpportunity__c po : pOpportunitys) {              
            // フェーズが受付で査定依頼日が未入力のとき、査定依頼日に当日をセット
            if (po.Phase__c == '受付' && po.RequestDate__c == null){
        		po.RequestDate__c = date.today();            
    		}            
    
            // フェーズが保留で査定日が未入力のとき、査定日に当日をセット
            if (po.Phase__c == '保留' && po.AssessmentDate__c == null){
        		po.AssessmentDate__c = date.today();            
    		}            
    
            // フェーズが買取で買取日が未入力のとき、買取日に当日をセット 
            if (po.Phase__c == '買取' && po.PurchaseDate__c == null){
        		po.PurchaseDate__c = date.today();            
    		}            
    
            // フェーズが全完了で全完了日が未入力のとき、全完了日に当日をセット
            if (po.Phase__c == '全完了' && po.CompletionDate__c == null){
        		po.CompletionDate__c = date.today();            
    		}            
    
            // フェーズがキャンセルでキャンセル日が未入力のとき、キャンセル日に当日をセット
            if (po.Phase__c == 'キャンセル' && po.CancelDate__c == null){
        		po.CancelDate__c = date.today();            
    		}            
    
            // 搬入日が未入力のとき、搬入日に引取日をセット
            if (po.CarryDate__c ==  null){
        		po.CarryDate__c = po.TakeUpDate__c;            
    		}            
        }        
    }        
}