force-app/main/default/objects/PurchaseExperienceWork__c/PurchaseExperienceWork__c.object-meta.xml
<CustomObject>
    <label>買取実績（ワーク）</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>買取実績（ワーク）No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchaseExperienceWork__c/fields/BudgetActualType__c.field-meta.xml
<CustomField>
    <fullName>BudgetActualType__c</fullName>
    <label>予実区分</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PurchaseExperienceWork__c/fields/PurchaseOpportunity__c.field-meta.xml
<CustomField>
    <fullName>PurchaseOpportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>買取商談</label>
    <referenceTo>PurchaseOpportunity__c</referenceTo>
    <relationshipLabel>買取実績（ワーク）</relationshipLabel>
    <relationshipName>OpportunityPurchaseExperience</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PurchaseExperienceWork__c/fields/UserCode__c.field-meta.xml
<CustomField>
    <fullName>UserCode__c</fullName>
    <label>社員コード</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunity__c/PurchaseOpportunity__c.object-meta.xml
<CustomObject>
    <label>買取商談</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>買取商談No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchaseOpportunity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>買取商談</relationshipLabel>
    <relationshipName>AccountOpportunity</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunity__c/fields/AssessmentDate__c.field-meta.xml
<CustomField>
    <fullName>AssessmentDate__c</fullName>
    <inlineHelpText>未入力でフェーズが保留の時、当日が自動的にセットされます。</inlineHelpText>
    <label>査定日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunity__c/fields/CorporationID__c.field-meta.xml
<CustomField>
    <fullName>CorporationID__c</fullName>
    <description>法人管理システムと連携するための連携項目、入力されているのはロット番号</description>
    <externalId>true</externalId>
    <inlineHelpText>法人のみ使用。基幹から読み込むためのＩＤ。</inlineHelpText>
    <label>法人ID</label>
    <length>20</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/PurchaseOpportunity__c/fields/OpportunityType__c.field-meta.xml
<CustomField>
    <fullName>OpportunityType__c</fullName>
    <description>買取商談作成時に取引先の取引種別が転記される（新規、既存、過去既存）</description>
    <inlineHelpText>買取商談作成時点での取引先の取引種別が転記されます。変更不可。</inlineHelpText>
    <label>商談種別</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>既存</fullName>
                <color>#0B6FCE</color>
                <label>既存</label>
            </value>
            <value>
                <fullName>新規</fullName>
                <color>#FF6666</color>
                <label>新規</label>
            </value>
            <value>
                <fullName>過去既存</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PurchaseOpportunity__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <description>買取商談のフェーズのパスの元になっている項目</description>
    <inlineHelpText>【受付】TEL・FAX等の査定依頼が来た状態。（依頼査定の場合は必ず入力）【保留】査定済み、商談中。未成約状態。（現地で見つけた査定はココからスタート）【買取】成約済み。引取・出品・支払い等進行中【全完了】引取。出品・支払い・後処理等全ての処理が完了【キャンセル】買取できず。</inlineHelpText>
    <label>フェーズ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>受付</fullName>
                <default>true</default>
                <label>受付</label>
            </value>
            <value>
                <fullName>保留</fullName>
            </value>
            <value>
                <fullName>買取</fullName>
            </value>
            <value>
                <fullName>全完了</fullName>
            </value>
            <value>
                <fullName>キャンセル</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PurchaseOpportunity__c/fields/PurchaseDate__c.field-meta.xml
<CustomField>
    <fullName>PurchaseDate__c</fullName>
    <inlineHelpText>未入力でフェーズが買取の時、当日が自動的にセットされます。</inlineHelpText>
    <label>買取日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunityWork__c/PurchaseOpportunityWork__c.object-meta.xml
<CustomObject>
    <label>買取商談（ワーク）</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>買取商談（ワーク）No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchaseOpportunityWork__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>買取商談（ワーク）</relationshipLabel>
    <relationshipName>AccountOpportunityWork</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunityWork__c/fields/AssessmentDate__c.field-meta.xml
<CustomField>
    <fullName>AssessmentDate__c</fullName>
    <label>査定日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunityWork__c/fields/CorporationID__c.field-meta.xml
<CustomField>
    <fullName>CorporationID__c</fullName>
    <externalId>true</externalId>
    <label>法人ID</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunityWork__c/fields/OpportunityType__c.field-meta.xml
<CustomField>
    <fullName>OpportunityType__c</fullName>
    <label>商談種別</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunityWork__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>フェーズ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunityWork__c/fields/PurchaseDate__c.field-meta.xml
<CustomField>
    <fullName>PurchaseDate__c</fullName>
    <label>買取日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/NXI_TestDataFactory.cls
@isTest
public class NXI_TestDataFactory {
    //**取引先**
    public static Account createAccount(String accountCode) {
        Account account = new Account();
        account.Name = 'テスト取引先';
        account.TradeType__c = '新規';
        account.CorporationType__c = '一般';
        account.AccountCode__c = accountCode;
        
        insert account;
        return account;
    }
    
    //**買取商談**
    public static PurchaseOpportunity__c createPurchaseOpportunity(Account account, String corporationId) {
        PurchaseOpportunity__c purchaseOpportunity = new PurchaseOpportunity__c();
        purchaseOpportunity.Account__c = account.Id;
        purchaseOpportunity.OpportunityType__c = '既存';
        purchaseOpportunity.Phase__c = '買取';
        purchaseOpportunity.CorporationID__c = corporationId;
        purchaseOpportunity.AssessmentDate__c=date.today();
        purchaseOpportunity.PurchaseDate__c=date.today();
        
        insert purchaseOpportunity;
        return purchaseOpportunity;
    }
    
    //**買取商談（ワーク）**
    public static PurchaseOpportunityWork__c createPurchaseOpportunityWork(Account account, String corporationId, String userCode) {
        PurchaseOpportunityWork__c purchaseOpportunityWork = new PurchaseOpportunityWork__c();
        purchaseOpportunityWork.Account__c = account.Id;
        purchaseOpportunityWork.OpportunityType__c = '既存';
        purchaseOpportunityWork.Phase__c = '買取';
        purchaseOpportunityWork.CorporationID__c = corporationId;
        purchaseOpportunityWork.UserCode__c = userCode;
        
        insert purchaseOpportunityWork;
        return purchaseOpportunityWork;
    }
    
     //**買取実績（ワーク）**
     public static PurchaseExperienceWork__c createPurchaseExperienceWork(PurchaseOpportunity__c purchaseOpportunity, String userCode) {
        PurchaseExperienceWork__c purchaseExperienceWork = new PurchaseExperienceWork__c();
        purchaseExperienceWork.PurchaseOpportunity__c = purchaseOpportunity.Id;
        purchaseExperienceWork.BudgetActualType__c = '実績';
        purchaseExperienceWork.UserCode__c = userCode;
        
        insert purchaseExperienceWork;
        return purchaseExperienceWork;
    }
}