force-app/main/default/objects/PurchaseExperienceWork__c/PurchaseExperienceWork__c.object-meta.xml
<CustomObject>
    <label>買取実績（ワーク）</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>買取実績（ワーク）No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchaseExperienceWork__c/fields/PurchaseOpportunity__c.field-meta.xml
<CustomField>
    <fullName>PurchaseOpportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>買取商談</label>
    <referenceTo>PurchaseOpportunity__c</referenceTo>
    <relationshipLabel>買取実績（ワーク）</relationshipLabel>
    <relationshipName>OpportunityPurchaseExperience</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunity__c/PurchaseOpportunity__c.object-meta.xml
<CustomObject>
    <label>買取商談</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>買取商談No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/classes/NXI_PExperienceWorkTriggerHandlerTest.cls
@isTest
public class NXI_PExperienceWorkTriggerHandlerTest {
    @isTest static void test() {
        Account account = NXI_TestDataFactory.createAccount('0000');
        PurchaseOpportunity__c purchaseOpportunity = NXI_TestDataFactory.createPurchaseOpportunity(account, '0000');
        PurchaseExperienceWork__c purchaseExperienceWork = NXI_TestDataFactory.createPurchaseExperienceWork(purchaseOpportunity, '0000');
    }
}