force-app/main/default/objects/AuctionInformation__c/AuctionInformation__c.object-meta.xml
<CustomObject>
    <label>オークション情報</label>
    <nameField>
        <displayFormat>A{0000000000}</displayFormat>
        <label>オークション情報名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AuctionInformation__c/fields/auc_sales_price__c.field-meta.xml
<CustomField>
    <fullName>auc_sales_price__c</fullName>
    <label>売却金額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/car_grade__c.field-meta.xml
<CustomField>
    <fullName>car_grade__c</fullName>
    <label>グレード</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/car_model__c.field-meta.xml
<CustomField>
    <fullName>car_model__c</fullName>
    <label>車種</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/car_type__c.field-meta.xml
<CustomField>
    <fullName>car_type__c</fullName>
    <label>型式</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/cell__c.field-meta.xml
<CustomField>
    <fullName>cell__c</fullName>
    <label>セル</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/ControlNumber__c.field-meta.xml
<CustomField>
    <fullName>ControlNumber__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>管理番号</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/engine__c.field-meta.xml
<CustomField>
    <fullName>engine__c</fullName>
    <label>エンジン</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/jiso__c.field-meta.xml
<CustomField>
    <fullName>jiso__c</fullName>
    <label>自走</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/registerdAtYear__c.field-meta.xml
<CustomField>
    <fullName>registerdAtYear__c</fullName>
    <label>年式</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/run_dist__c.field-meta.xml
<CustomField>
    <fullName>run_dist__c</fullName>
    <label>走行距離</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/SoldData__c.field-meta.xml
<CustomField>
    <fullName>SoldData__c</fullName>
    <label>売却日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ContentVersionTriggerHelper.cls
public without sharing class ContentVersionTriggerHelper {
    public ContentVersionTriggerHelper() {

    }

    public void CreateAuctionInfo(List<ContentVersion> targetList) {
        System.debug('■■■ CreateAuctionInfo-START ■■■');

        // オークション情報の作成
        Map<String, AuctionInformation__c> tempAuctionInfoMap = new Map<String, AuctionInformation__c>();
        for (ContentVersion cv : targetList) {
            if (!cv.isSet('ControlNumber__c') || cv.ControlNumber__c == ''){
                // オークション以外の画像なのでスキップ
                continue;
            }
            if (tempAuctionInfoMap.containsKey(cv.ControlNumber__c)) {
                // オークション作成済みなのでスキップ
                continue;
            }
            AuctionInformation__c auctionInfo = new AuctionInformation__c();
            auctionInfo.cell__c = cv.cell__c;                                   // セル
            auctionInfo.jiso__c = cv.jiso__c;                                   // 自走
            auctionInfo.engine__c = cv.engine__c;                               // エンジン
            auctionInfo.SoldData__c = cv.SoldData__c;                           // 売却日
            auctionInfo.car_type__c = cv.car_type__c;                           // 車種
            auctionInfo.car_grade__c = cv.car_grade__c;                         // グレード
            auctionInfo.car_model__c = cv.car_model__c;                         // 型式
            auctionInfo.ControlNumber__c = cv.ControlNumber__c;                 // 管理番号
            auctionInfo.registerdAtYear__c = cv.registerdAtYear__c;             // 年式
            auctionInfo.auc_sales_price__c = cv.auc_sales_price__c;             // 売却金額
            if (String.isNotBlank(cv.run_dist__c)) {
                auctionInfo.run_dist__c = Decimal.valueOf(cv.run_dist__c);      // 走行距離
            }
            // insert用のリストに追加
            tempAuctionInfoMap.put(auctionInfo.ControlNumber__c, auctionInfo);
        }

        if (tempAuctionInfoMap.size() == 0){
            // オークション情報が無ければ何もせず終了
            return;
        }

        // オークション情報 upsert(管理番号(ControlNumber__c)をキーに設定する)
        List<AuctionInformation__c> auctionInfoList = new List<AuctionInformation__c>(tempAuctionInfoMap.values());
        upsert auctionInfoList ControlNumber__c;

        // insertしたオークション情報をMapにセットする(Key：管理番号, Value：オークション情報)
        Map<String, AuctionInformation__c> auctionInfoMap = new Map<String, AuctionInformation__c>();
        for (AuctionInformation__c auc : auctionInfoList) {
            auctionInfoMap.put(auc.ControlNumber__c, auc);
        }

        // コンテンツドキュメントリンクの作成
        List<ContentDocumentLink> cdlList = new List<ContentDocumentLink>();
        for (ContentVersion tempCv : targetList) {
            ContentDocumentLink cdl = new ContentDocumentLink();
            if (auctionInfoMap.containsKey(tempCv.ControlNumber__c)) {
                cdl.LinkedEntityId = auctionInfoMap.get(tempCv.ControlNumber__c).Id;    // リンク済みエンティティID(リンクするオブジェクトのレコードID)
                cdl.ContentDocumentId = tempCv.ContentDocumentId;                       // コンテンツドキュメントID(添付ファイルのID)
                cdl.Visibility = Constants.CDL_VISIBILITY_ALL_USERS;                    // 表示
                cdl.ShareType = Constants.CDL_SHARE_TYPE_V;                             // 共有種別
                cdlList.add(cdl);
            }
        }

        // コンテンツドキュメントリンク insert
        insert cdlList;

        System.debug('■■■ CreateAuctionInfo-END ■■■');
    }
}