force-app/main/default/objects/AuctionInformation__c/AuctionInformation__c.object-meta.xml
<CustomObject>
    <label>オークション情報</label>
    <nameField>
        <displayFormat>A{0000000000}</displayFormat>
        <label>オークション情報名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AuctionInformation__c/fields/auc_sales_price__c.field-meta.xml
<CustomField>
    <fullName>auc_sales_price__c</fullName>
    <label>売却金額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/car_grade__c.field-meta.xml
<CustomField>
    <fullName>car_grade__c</fullName>
    <label>グレード</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/car_model__c.field-meta.xml
<CustomField>
    <fullName>car_model__c</fullName>
    <label>車種</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/car_type__c.field-meta.xml
<CustomField>
    <fullName>car_type__c</fullName>
    <label>型式</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/cell__c.field-meta.xml
<CustomField>
    <fullName>cell__c</fullName>
    <label>セル</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/ControlNumber__c.field-meta.xml
<CustomField>
    <fullName>ControlNumber__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>管理番号</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/engine__c.field-meta.xml
<CustomField>
    <fullName>engine__c</fullName>
    <label>エンジン</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/jiso__c.field-meta.xml
<CustomField>
    <fullName>jiso__c</fullName>
    <label>自走</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/registerdAtYear__c.field-meta.xml
<CustomField>
    <fullName>registerdAtYear__c</fullName>
    <label>年式</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/run_dist__c.field-meta.xml
<CustomField>
    <fullName>run_dist__c</fullName>
    <label>走行距離</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/SoldData__c.field-meta.xml
<CustomField>
    <fullName>SoldData__c</fullName>
    <label>売却日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ContentVersionTriggerTest.cls
@isTest
public without sharing class ContentVersionTriggerTest {
    testmethod private static void testContentVersionTrigger(){
        // テストデータ作成
        List<ContentVersion> contentVersionList = new List<ContentVersion>();
        ContentVersion cv = new ContentVersion();
        Integer createAuctionRecord = 20;
        Integer createContentRecord = 6;
        for(Integer i=1; i<=createAuctionRecord; i++){
            String title = '1';
            for(Integer j=1; j<=createContentRecord; j++){
                cv = new ContentVersion();
                cv.Title = title;                                                 // タイトル
                cv.cell__c = '回る';                                              // セル
                cv.jiso__c = '可';                                                // 自走
                cv.engine__c = 'かかる';                                          // エンジン
                cv.SoldData__c = Date.parse('2020/10/01');                        // 売却日
                cv.car_type__c = 'アクア';                                        // 車種
                cv.car_grade__c = 'L';                                            // グレード
                cv.car_model__c = 'DAA-MK42S';                                    // 型式
                cv.ControlNumber__c = '201205_' + String.valueOf(i).leftPad(8, '0');                      // 管理番号
                cv.registerdAtYear__c = '2019';                                   // 年式
                cv.auc_sales_price__c = Decimal.valueOf(500000);                  // 売却金額
                cv.run_dist__c = '35000';                                         // 走行距離
                cv.PathOnClient = 'expense.csv';
                cv.VersionData = Blob.valueOf('expense.csv');

                contentVersionList.add(cv);
            }
            Integer titleIncrease = Integer.valueOf(title);
            titleIncrease += 1;
            title = String.valueOf(titleIncrease);
        }
        // テスト開始
        Test.startTest();
        // コンテンツバージョンをinsertする
        insert contentVersionList;
        System.assertEquals(cv.cell__c, contentVersionList[0].cell__c);
        // オークション情報取得
        List<AuctionInformation__c> aucList = [SELECT cell__c FROM AuctionInformation__c];
        System.assertEquals(aucList[0].cell__c, contentVersionList[0].cell__c);
        // コンテンツドキュメントリンクの情報取得
        // List<ContentDocumentLink> cdlList = [SELECT LinkedEntityId FROM ContentDocumentLink];
        // System.debug(cdlList[0]);
        // テスト終了
        Test.stopTest();
    }
    testmethod private static void testContentVersionTrigger_otherAuction(){
        // テストデータ作成
        List<ContentVersion> contentVersionList = new List<ContentVersion>();
        ContentVersion cv = new ContentVersion();
        Integer createAuctionRecord = 20;
        Integer createContentRecord = 6;
        for(Integer i=1; i<=createAuctionRecord; i++){
            for(Integer j=1; j<=createContentRecord; j++){
                cv = new ContentVersion();
                cv.PathOnClient = 'expense.csv';
                cv.VersionData = Blob.valueOf('expense.csv');

                contentVersionList.add(cv);
            }
        }
        // テスト開始
        Test.startTest();
        // コンテンツバージョンをinsertする
        insert contentVersionList;
        // オークション情報取得
        List<AuctionInformation__c> aucList = [SELECT Id FROM AuctionInformation__c];
        System.assertEquals(aucList.size(), 0);
        Test.stopTest();
    }
}