force-app/main/default/objects/AuctionInformation__c/AuctionInformation__c.object-meta.xml
<CustomObject>
    <label>オークション情報</label>
    <nameField>
        <displayFormat>A{0000000000}</displayFormat>
        <label>オークション情報名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AuctionInformation__c/fields/auc_sales_price__c.field-meta.xml
<CustomField>
    <fullName>auc_sales_price__c</fullName>
    <label>売却金額</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/car_grade__c.field-meta.xml
<CustomField>
    <fullName>car_grade__c</fullName>
    <label>グレード</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/car_model__c.field-meta.xml
<CustomField>
    <fullName>car_model__c</fullName>
    <label>車種</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/car_type__c.field-meta.xml
<CustomField>
    <fullName>car_type__c</fullName>
    <label>型式</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/cell__c.field-meta.xml
<CustomField>
    <fullName>cell__c</fullName>
    <label>セル</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/ControlNumber__c.field-meta.xml
<CustomField>
    <fullName>ControlNumber__c</fullName>
    <caseSensitive>true</caseSensitive>
    <externalId>true</externalId>
    <label>管理番号</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/engine__c.field-meta.xml
<CustomField>
    <fullName>engine__c</fullName>
    <label>エンジン</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/jiso__c.field-meta.xml
<CustomField>
    <fullName>jiso__c</fullName>
    <label>自走</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/registerdAtYear__c.field-meta.xml
<CustomField>
    <fullName>registerdAtYear__c</fullName>
    <label>年式</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/run_dist__c.field-meta.xml
<CustomField>
    <fullName>run_dist__c</fullName>
    <label>走行距離</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/AuctionInformation__c/fields/SoldData__c.field-meta.xml
<CustomField>
    <fullName>SoldData__c</fullName>
    <label>売却日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/AuctionInfoDao.cls
public without sharing class AuctionInfoDao {
    // コンストラクタ
    public AuctionInfoDao() {
    }

    public List<AuctionInformation__c> getAuctionInfo(String carModel, String carType, String carYear, String sortKey, String order) {
        // SELECT
        String soqlBase = '';
        soqlBase += ' SELECT ';
        soqlBase += ' Id ';
        soqlBase += ' , Name ';                 // 名前
        soqlBase += ' , car_type__c ';          // 型式
        soqlBase += ' , car_model__c ';         // 車種
        soqlBase += ' , car_grade__c ';         // グレード
        soqlBase += ' , engine__c ';            // エンジン
        soqlBase += ' , cell__c ';              // セル
        soqlBase += ' , SoldData__c ';          // 売却日
        soqlBase += ' , auc_sales_price__c ';   // 売却金額
        soqlBase += ' , registerdAtYear__c ';   // 年式
        soqlBase += ' , ControlNumber__c ';     // 管理番号
        soqlBase += ' , jiso__c ';              // 自走
        soqlBase += ' , run_dist__c ';          // 走行距離
        soqlBase += ' FROM ';
        soqlBase += ' AuctionInformation__c ';

        // WHERE
        String SoqlWhere = ' WHERE ';

        // 車種(検索値がある場合、検索条件に追加)
        if (String.isNotBlank(carModel)) {
            SoqlWhere += 'car_model__c = ' + '\'' + carModel + '\'';
        }else{
            SoqlWhere += 'car_model__c = ' + null;
        }
        
        // 型式(検索値がある場合、検索条件に追加)
        if (String.isNotBlank(carType)) {
            SoqlWhere += ' AND (car_type__c = ' + null + ' OR car_type__c = ' + '\'' + carType + '\')';
        }
        
        // 年式(検索値がある場合、検索条件に追加)
        if (String.isNotBlank(carYear)) {
            SoqlWhere += ' AND (registerdAtYear__c = ' + null + ' OR registerdAtYear__c = ' + '\'' + carYear + '\')';
        }

        // ORDER BY
        String soqlOrder = '';
        soqlOrder += ' ORDER BY ' + sortKey + ' ' + order;
        // クエリ実行
        List<AuctionInformation__c> auctionInfoList = Database.query(soqlBase + soqlWhere + soqlOrder);
        return auctionInfoList;
    }
    
    /**
     * コンテンツドキュメントリンクを取得する
     * コンテンツドキュメントリンクを軸に、親のコンテンツドキュメントから以下の項目を取得する
     * ・タイトル
     * ・最新の公開バージョンID（ContentsVersionのID）
     * 
     */
    public List<ContentDocumentLink> getContentDocumentLink(Set<Id> objectId) {
        system.debug('TargetLinkedEntityId');
        system.debug(objectId);
        List<ContentDocumentLink> linkList = [ SELECT ContentDocumentId                             // コンテンツドキュメントID
                                                    , Id                                            // ID
                                                    , LinkedEntityId                                // リンク済みエンティティID
                                                    , ContentDocument.Title                         // コンテンツドキュメント.タイトル
                                                    , ContentDocument.LatestPublishedVersionId      // 最新の公開バージョンID
                                                    FROM ContentDocumentLink
                                                    WHERE LinkedEntityId = :objectId ];
        return linkList;
    }

}