force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>査定表</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>査定表名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/asses_date__c.field-meta.xml
<CustomField>
    <fullName>asses_date__c</fullName>
    <label>査定年月日</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/asses_tanto__c.field-meta.xml
<CustomField>
    <fullName>asses_tanto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>査定担当者</label>
    <referenceTo>Mst_Assess_Users__c</referenceTo>
    <relationshipLabel>査定表</relationshipLabel>
    <relationshipName>assessments_user</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/asset_mngno__c.field-meta.xml
<CustomField>
    <fullName>asset_mngno__c</fullName>
    <externalId>true</externalId>
    <label>査定表管理No.</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/suspended_flg__c.field-meta.xml
<CustomField>
    <fullName>suspended_flg__c</fullName>
    <defaultValue>false</defaultValue>
    <label>中断フラグ</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Assessment__c/recordTypes/yard.recordType-meta.xml
<RecordType>
    <fullName>yard</fullName>
    <active>true</active>
    <description>ヤード査定表</description>
    <label>ヤード</label>
</RecordType>

force-app/main/default/objects/Mst_Assess_Users__c/Mst_Assess_Users__c.object-meta.xml
<CustomObject>
    <description>査定アプリユーザ管理用オブジェクト（正社員および業者）</description>
    <label>査定ユーザ</label>
    <nameField>
        <label>査定ユーザ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mst_Assess_Users__c/fields/emp_kind__c.field-meta.xml
<CustomField>
    <fullName>emp_kind__c</fullName>
    <label>社員区分</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>営業ユーザ</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>ヤードユーザ</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>取引先</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>提携業者様</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>外部ユーザ</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Mst_Assess_Users__c/fields/login_user__c.field-meta.xml
<CustomField>
    <fullName>login_user__c</fullName>
    <externalId>true</externalId>
    <label>ログインID</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Mst_Assess_Users__c/fields/pass__c.field-meta.xml
<CustomField>
    <fullName>pass__c</fullName>
    <label>パスワード</label>
    <length>16</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/AssessmentGetBatchTest.cls
@istest
public without sharing class AssessmentGetBatchTest {
    public AssessmentGetBatchTest() {
    }

    testmethod private static void testAssessmentBatchExecuteSuccess(){
        Test.setMock(HttpCalloutMock.class, new AssessmentDetailTestCalloutMock());
        executeTest();
        // Apexをスケジュールに登録
        String jobId = System.schedule('TestScheduledApex','0 0 * * * ?', new AssessmentGetBatchSchedule());
        List<Assessment__c> postSuccess;
        postSuccess = [Select Name From Assessment__c Where SendDateToAuctionSite__c != null];
        System.assertEquals(postSuccess.size(), 5, 'success');
    }

    testmethod private static void testAssessmentBatchExecuteFailed(){
        Test.setMock(HttpCalloutMock.class, new AssessmentDetailTestCalloutMockError());
        executeTest();
        // Apexをスケジュールに登録
        String jobId = System.schedule('TestScheduledApex','0 0 * * * ?', new AssessmentGetBatchSchedule());
        List<Assessment__c> postError;
        postError = [Select Name From Assessment__c Where error_flg__c = true];
        System.assertEquals(postError.size(), 5, 'failed');
    }

    //査定ユーザ作成
    private static void executeTest(){
        Mst_Assess_Users__c sobj = new Mst_Assess_Users__c(
            Name = 'test',
            emp_kind__c = '0',
            login_user__c = 'test',
            pass__c = 'test'
        );
        insert sobj;

        //ヤードレコードタイプId取得
        RecordType RecordTypeYardId = [select Id from RecordType where DeveloperName = 'yard' And SObjectType = 'Assessment__c' Limit 1];
        List<Assessment__c> data = new List<Assessment__c>();
        
        for(integer i=0;i<5;i++){
            data.add(new Assessment__c(
                //ヤード査定表作成
                suspended_flg__c = false,                                 // 中断フラグ
                error_flg__c = false,                                     // エラーフラグ
                asses_date__c = Datetime.valueOf('2020-10-23 12:00:00'),  // 査定年月日
                asses_tanto__c = sobj.Id,                                 // 査定担当者
                asset_mngno__c = '00000'+ i.format(),                     // 査定表管理No.
                tokki_inner__c = '室内ばらし',
                RecordTypeId = RecordTypeYardId.Id));

            data.add( new Assessment__c(
                //営業査定表作成
                suspended_flg__c = false,                                 // 中断フラグ
                error_flg__c = false,                                     // エラーフラグ
                asses_date__c = Datetime.valueOf('2020-10-23 12:00:00'),  // 査定年月日
                asses_tanto__c = sobj.Id,                                 // 査定担当者
                asset_mngno__c = '11111'+i.format(),                      // 査定表管理No.
                tokki_inner__c = '室内ばらし'));
        }
        insert data;

        System.assertEquals(data.size(), 10);

        Test.startTest();
        AssessmentGetBatch batch = new AssessmentGetBatch();
        Database.QueryLocator ql = batch.start(null);
        List<Assessment__c> dataList = new List<Assessment__c>();
        
        Database.QueryLocatorIterator it =  ql.iterator();
        while (it.hasNext())
        {
            dataList.add((Assessment__c)it.next());
        }

        batch.execute(null,dataList);
        batch.finish(null);
        Test.stopTest();
    }
}