force-app/main/default/objects/AccountAssessment__c/AccountAssessment__c.object-meta.xml
<CustomObject>
    <label>取引先査定表</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>取引先査定表名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/AccountAssessment__c/fields/asses_tanto__c.field-meta.xml
<CustomField>
    <fullName>asses_tanto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>査定担当者</label>
    <referenceTo>Mst_Assess_Users__c</referenceTo>
    <relationshipLabel>査定表</relationshipLabel>
    <relationshipName>account_assessments_user</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/asset_mngno__c.field-meta.xml
<CustomField>
    <fullName>asset_mngno__c</fullName>
    <externalId>true</externalId>
    <label>査定表管理No.</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/cotion_url__c.field-meta.xml
<CustomField>
    <fullName>cotion_url__c</fullName>
    <label>コーションURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/front_seat_url__c.field-meta.xml
<CustomField>
    <fullName>front_seat_url__c</fullName>
    <label>前席シートURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/left_back_url__c.field-meta.xml
<CustomField>
    <fullName>left_back_url__c</fullName>
    <label>左後ろURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/left_front_url__c.field-meta.xml
<CustomField>
    <fullName>left_front_url__c</fullName>
    <label>左前URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/meter_url__c.field-meta.xml
<CustomField>
    <fullName>meter_url__c</fullName>
    <label>メーターURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/other_url_04__c.field-meta.xml
<CustomField>
    <fullName>other_url_04__c</fullName>
    <label>その他URL4</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/other_url_05__c.field-meta.xml
<CustomField>
    <fullName>other_url_05__c</fullName>
    <label>その他URL5</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/other_url_06__c.field-meta.xml
<CustomField>
    <fullName>other_url_06__c</fullName>
    <label>その他URL6</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/other_url_09__c.field-meta.xml
<CustomField>
    <fullName>other_url_09__c</fullName>
    <label>その他URL9</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/other_url_10__c.field-meta.xml
<CustomField>
    <fullName>other_url_10__c</fullName>
    <label>その他URL10</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/other_url_11__c.field-meta.xml
<CustomField>
    <fullName>other_url_11__c</fullName>
    <label>その他URL11</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/other_url_13__c.field-meta.xml
<CustomField>
    <fullName>other_url_13__c</fullName>
    <label>その他URL13</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/other_url_14__c.field-meta.xml
<CustomField>
    <fullName>other_url_14__c</fullName>
    <label>その他URL14</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/other_url_16__c.field-meta.xml
<CustomField>
    <fullName>other_url_16__c</fullName>
    <label>その他URL16</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/other_url_19__c.field-meta.xml
<CustomField>
    <fullName>other_url_19__c</fullName>
    <label>その他URL19</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/other_url_21__c.field-meta.xml
<CustomField>
    <fullName>other_url_21__c</fullName>
    <label>その他URL21</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/other_url_23__c.field-meta.xml
<CustomField>
    <fullName>other_url_23__c</fullName>
    <label>その他URL23</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/other_url_28__c.field-meta.xml
<CustomField>
    <fullName>other_url_28__c</fullName>
    <label>その他URL28</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/other_url_29__c.field-meta.xml
<CustomField>
    <fullName>other_url_29__c</fullName>
    <label>その他URL29</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/other_url_33__c.field-meta.xml
<CustomField>
    <fullName>other_url_33__c</fullName>
    <label>その他URL33</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/other_url_34__c.field-meta.xml
<CustomField>
    <fullName>other_url_34__c</fullName>
    <label>その他URL34</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/other_url_35__c.field-meta.xml
<CustomField>
    <fullName>other_url_35__c</fullName>
    <label>その他URL35</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/other_url_40__c.field-meta.xml
<CustomField>
    <fullName>other_url_40__c</fullName>
    <label>その他URL40</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/room_url__c.field-meta.xml
<CustomField>
    <fullName>room_url__c</fullName>
    <label>室内URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/steering_url__c.field-meta.xml
<CustomField>
    <fullName>steering_url__c</fullName>
    <label>ステアリングURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/switch1_url__c.field-meta.xml
<CustomField>
    <fullName>switch1_url__c</fullName>
    <label>スイッチ類①URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/AccountAssessment__c/fields/switch2_url__c.field-meta.xml
<CustomField>
    <fullName>switch2_url__c</fullName>
    <label>スイッチ類②URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/Assessment__c.object-meta.xml
<CustomObject>
    <label>査定表</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>査定表名</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Assessment__c/fields/asses_tanto__c.field-meta.xml
<CustomField>
    <fullName>asses_tanto__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>査定担当者</label>
    <referenceTo>Mst_Assess_Users__c</referenceTo>
    <relationshipLabel>査定表</relationshipLabel>
    <relationshipName>assessments_user</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/asset_mngno__c.field-meta.xml
<CustomField>
    <fullName>asset_mngno__c</fullName>
    <externalId>true</externalId>
    <label>査定表管理No.</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/center_console_url__c.field-meta.xml
<CustomField>
    <fullName>center_console_url__c</fullName>
    <label>センターコンソールURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/engine_url__c.field-meta.xml
<CustomField>
    <fullName>engine_url__c</fullName>
    <label>エンジンルームURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/front_url__c.field-meta.xml
<CustomField>
    <fullName>front_url__c</fullName>
    <label>正面URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/key_url__c.field-meta.xml
<CustomField>
    <fullName>key_url__c</fullName>
    <label>カギURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/other_url_01__c.field-meta.xml
<CustomField>
    <fullName>other_url_01__c</fullName>
    <label>その他URL1</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/other_url_02__c.field-meta.xml
<CustomField>
    <fullName>other_url_02__c</fullName>
    <label>その他URL2</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/other_url_03__c.field-meta.xml
<CustomField>
    <fullName>other_url_03__c</fullName>
    <label>その他URL3</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/other_url_07__c.field-meta.xml
<CustomField>
    <fullName>other_url_07__c</fullName>
    <label>その他URL7</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/other_url_08__c.field-meta.xml
<CustomField>
    <fullName>other_url_08__c</fullName>
    <label>その他URL8</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/other_url_12__c.field-meta.xml
<CustomField>
    <fullName>other_url_12__c</fullName>
    <label>その他URL12</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/other_url_15__c.field-meta.xml
<CustomField>
    <fullName>other_url_15__c</fullName>
    <label>その他URL15</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/other_url_17__c.field-meta.xml
<CustomField>
    <fullName>other_url_17__c</fullName>
    <label>その他URL17</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/other_url_18__c.field-meta.xml
<CustomField>
    <fullName>other_url_18__c</fullName>
    <label>その他URL18</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/other_url_20__c.field-meta.xml
<CustomField>
    <fullName>other_url_20__c</fullName>
    <label>その他URL20</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/other_url_22__c.field-meta.xml
<CustomField>
    <fullName>other_url_22__c</fullName>
    <label>その他URL22</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/other_url_24__c.field-meta.xml
<CustomField>
    <fullName>other_url_24__c</fullName>
    <label>その他URL24</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/other_url_25__c.field-meta.xml
<CustomField>
    <fullName>other_url_25__c</fullName>
    <label>その他URL25</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/other_url_26__c.field-meta.xml
<CustomField>
    <fullName>other_url_26__c</fullName>
    <label>その他URL26</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/other_url_27__c.field-meta.xml
<CustomField>
    <fullName>other_url_27__c</fullName>
    <label>その他URL27</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/other_url_30__c.field-meta.xml
<CustomField>
    <fullName>other_url_30__c</fullName>
    <label>その他URL30</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/other_url_31__c.field-meta.xml
<CustomField>
    <fullName>other_url_31__c</fullName>
    <label>その他URL31</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/other_url_32__c.field-meta.xml
<CustomField>
    <fullName>other_url_32__c</fullName>
    <label>その他URL32</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/other_url_36__c.field-meta.xml
<CustomField>
    <fullName>other_url_36__c</fullName>
    <label>その他URL36</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/other_url_37__c.field-meta.xml
<CustomField>
    <fullName>other_url_37__c</fullName>
    <label>その他URL37</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/other_url_38__c.field-meta.xml
<CustomField>
    <fullName>other_url_38__c</fullName>
    <label>その他URL38</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/other_url_39__c.field-meta.xml
<CustomField>
    <fullName>other_url_39__c</fullName>
    <label>その他URL39</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/right_back_url__c.field-meta.xml
<CustomField>
    <fullName>right_back_url__c</fullName>
    <label>右後ろURL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/right_front_url__c.field-meta.xml
<CustomField>
    <fullName>right_front_url__c</fullName>
    <label>右前URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Assessment__c/fields/shakensho_url__c.field-meta.xml
<CustomField>
    <fullName>shakensho_url__c</fullName>
    <label>車検証URL</label>
    <type>Url</type>
</CustomField>

force-app/main/default/objects/Mst_Assess_Users__c/Mst_Assess_Users__c.object-meta.xml
<CustomObject>
    <description>査定アプリユーザ管理用オブジェクト（正社員および業者）</description>
    <label>査定ユーザ</label>
    <nameField>
        <label>査定ユーザ名</label>
        <type>Text</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Mst_Assess_Users__c/fields/emp_kind__c.field-meta.xml
<CustomField>
    <fullName>emp_kind__c</fullName>
    <label>社員区分</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>0</fullName>
                <label>営業ユーザ</label>
            </value>
            <value>
                <fullName>3</fullName>
                <label>ヤードユーザ</label>
            </value>
            <value>
                <fullName>2</fullName>
                <label>取引先</label>
            </value>
            <value>
                <fullName>1</fullName>
                <label>提携業者様</label>
            </value>
            <value>
                <fullName>4</fullName>
                <label>外部ユーザ</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/AssessPictureControllerTest.cls
@isTest
private class AssessPictureControllerTest {

    static Id asses_tanto_id;
    static Id asses_account_tanto_id;

    @TestSetup
    static void makeAssesTanto(){
        TestDataFactory tdf = new TestDataFactory();
        Account account = tdf.createAccountData();
        Contact contact = tdf.createContactData2(account);
        tdf.createAssessUser();
        tdf.createAccountAssessUser(contact);
    }

    static Id getAssesTanto(String emp_kind){
        Mst_Assess_Users__c tanto = [SELECT Id FROM Mst_Assess_Users__c WHERE emp_kind__c = :emp_kind LIMIT 1];
        return tanto.Id;
    }

    //査定表で画像項目すべてセット
    @isTest
    static void testLoadRecordAssessment_SetAllImage() {

        //査定表テストデータの作成
        System.debug(getAssesTanto('1'));
        Assessment__c testAssessment = new Assessment__c(asses_tanto__c = getAssesTanto('1'), asset_mngno__c = '20241101_150000_001000');
        insert testAssessment;

        String imageColumnList = 'front_url__c,right_front_url__c,left_front_url__c,left_back_url__c,right_back_url__c,room_url__c,engine_url__c,cotion_url__c,key_url__c,meter_url__c,steering_url__c,center_console_url__c,front_seat_url__c,switch1_url__c,switch2_url__c,other_url_01__c,other_url_02__c,other_url_03__c,other_url_04__c,other_url_05__c,other_url_06__c,other_url_07__c,other_url_08__c,other_url_09__c,other_url_10__c,other_url_11__c,other_url_12__c,other_url_13__c,other_url_14__c,other_url_15__c,other_url_16__c,other_url_17__c,other_url_18__c,other_url_19__c,other_url_20__c,other_url_21__c,other_url_22__c,other_url_23__c,other_url_24__c,other_url_25__c,other_url_26__c,other_url_27__c,other_url_28__c,other_url_29__c,other_url_30__c,other_url_31__c,other_url_32__c,other_url_33__c,other_url_34__c,other_url_35__c,other_url_36__c,other_url_37__c,other_url_38__c,other_url_39__c,other_url_40__c,shakensho_url__c';
        String objectName = 'Assessment__c';
        String recordId = testAssessment.Id;

        for(Integer i = 0; i < imageColumnList.split(',').size(); i++){
            String key = imageColumnList.split(',')[i].trim();
            String value = 'https://'+key;
            testAssessment.put(key,value);
        }
        testAssessment.put('asses_tanto__c',getAssesTanto('1'));
        testAssessment.put('asset_mngno__c','20241101_150000_001000');
        update testAssessment;

        Test.startTest();
        Map<String, String> result = AssessPictureController.LoadRecord(imageColumnList, objectName, recordId);
        Test.stopTest();

        for(String col : imageColumnList.split(',')){
            String imageColum= col.trim();
            System.assertEquals('https://'+imageColum, result.get(imageColum), imageColum+'で期待される画像URLが一致しません。');
        }

    }

    //査定表で画像項目がすべて空
    @isTest
    static void testLoadRecordAssessment_SetNoImage() {

        //査定表テストデータの作成
        Assessment__c testAssessment = new Assessment__c(asses_tanto__c = getAssesTanto('1'), asset_mngno__c = '20241101_150000_001002');
        insert testAssessment;

        String imageColumnList = 'front_url__c,right_front_url__c,left_front_url__c,left_back_url__c,right_back_url__c,room_url__c,engine_url__c,cotion_url__c,key_url__c,meter_url__c,steering_url__c,center_console_url__c,front_seat_url__c,switch1_url__c,switch2_url__c,other_url_01__c,other_url_02__c,other_url_03__c,other_url_04__c,other_url_05__c,other_url_06__c,other_url_07__c,other_url_08__c,other_url_09__c,other_url_10__c,other_url_11__c,other_url_12__c,other_url_13__c,other_url_14__c,other_url_15__c,other_url_16__c,other_url_17__c,other_url_18__c,other_url_19__c,other_url_20__c,other_url_21__c,other_url_22__c,other_url_23__c,other_url_24__c,other_url_25__c,other_url_26__c,other_url_27__c,other_url_28__c,other_url_29__c,other_url_30__c,other_url_31__c,other_url_32__c,other_url_33__c,other_url_34__c,other_url_35__c,other_url_36__c,other_url_37__c,other_url_38__c,other_url_39__c,other_url_40__c,shakensho_url__c';
        String objectName = 'Assessment__c';
        String recordId = testAssessment.Id;

        Map<String, String> result = AssessPictureController.LoadRecord(imageColumnList, objectName, recordId);

        for(String col : imageColumnList.split(',')){
            String imageColum= col.trim();
            System.assertEquals(null, result.get(imageColum), imageColum+'で期待される画像URLが一致しません。');
            System.debug('すべて空Value:'+result.get(imageColum));
        }
    }

    //査定表で画像項目が一部設定、一部空
    @isTest
    static void testLoadRecordAssessment_SetSomeImage() {

        //査定表テストデータの作成
        Assessment__c testAssessment = new Assessment__c(asses_tanto__c = getAssesTanto('1'), asset_mngno__c = '20241101_150000_001003');
        insert testAssessment;

        String imageColumnList = 'front_url__c,right_front_url__c,left_front_url__c,left_back_url__c,right_back_url__c,room_url__c,engine_url__c,cotion_url__c,key_url__c,meter_url__c,steering_url__c,center_console_url__c,front_seat_url__c,switch1_url__c,switch2_url__c,other_url_01__c,other_url_02__c,other_url_03__c,other_url_04__c,other_url_05__c,other_url_06__c,other_url_07__c,other_url_08__c,other_url_09__c,other_url_10__c,other_url_11__c,other_url_12__c,other_url_13__c,other_url_14__c,other_url_15__c,other_url_16__c,other_url_17__c,other_url_18__c,other_url_19__c,other_url_20__c,other_url_21__c,other_url_22__c,other_url_23__c,other_url_24__c,other_url_25__c,other_url_26__c,other_url_27__c,other_url_28__c,other_url_29__c,other_url_30__c,other_url_31__c,other_url_32__c,other_url_33__c,other_url_34__c,other_url_35__c,other_url_36__c,other_url_37__c,other_url_38__c,other_url_39__c,other_url_40__c,shakensho_url__c';
        String objectName = 'Assessment__c';
        String recordId = testAssessment.Id;

        for(Integer i = 0; i < imageColumnList.split(',').size(); i++){
            String key = imageColumnList.split(',')[i].trim();
            String value = '';
            //正面、その他１のみ画像URLをセット
            if(key == 'front_url__c' || key == 'other_url_1__c'){
                value = 'https://'+key;
            }else{
                value ='';
            }
            testAssessment.put(key,value);
        }
        update testAssessment;

        Map<String, String> result = AssessPictureController.LoadRecord(imageColumnList, objectName, recordId);

        for(String col : imageColumnList.split(',')){
            String imageColum= col.trim();
            if(imageColum == 'front_url__c' || imageColum == 'other_url_1__c'){
                System.assertEquals('https://'+imageColum, result.get(imageColum), imageColum+'で期待される画像URLが一致しません。');
            }else{
                System.assertEquals(null, result.get(imageColum), imageColum+'で期待される画像URLが一致しません。');
            }
        }
    }
    //査定表で存在しない項目名の値セット（エラー確認用）
    @isTest
    static void testLoadRecordAssessment_InvalidColumn() {

        //査定表テストデータの作成
        Assessment__c testAssessment = new Assessment__c(asses_tanto__c = getAssesTanto('1'), asset_mngno__c = '20241101_150000_001004');
        insert testAssessment;

        String imageColumnList = 'errortest__c,right_front_url__c,left_front_url__c,left_back_url__c,right_back_url__c,room_url__c,engine_url__c,cotion_url__c,key_url__c,meter_url__c,steering_url__c,center_console_url__c,front_seat_url__c,switch1_url__c,switch2_url__c,other_url_01__c,other_url_02__c,other_url_03__c,other_url_04__c,other_url_05__c,other_url_06__c,other_url_07__c,other_url_08__c,other_url_09__c,other_url_10__c,other_url_11__c,other_url_12__c,other_url_13__c,other_url_14__c,other_url_15__c,other_url_16__c,other_url_17__c,other_url_18__c,other_url_19__c,other_url_20__c,other_url_21__c,other_url_22__c,other_url_23__c,other_url_24__c,other_url_25__c,other_url_26__c,other_url_27__c,other_url_28__c,other_url_29__c,other_url_30__c,other_url_31__c,other_url_32__c,other_url_33__c,other_url_34__c,other_url_35__c,other_url_36__c,other_url_37__c,other_url_38__c,other_url_39__c,other_url_40__c,shakensho_url__c';
        String imageColumnList_loop = 'front_url__c,right_front_url__c,left_front_url__c,left_back_url__c,right_back_url__c,room_url__c,engine_url__c,cotion_url__c,key_url__c,meter_url__c,steering_url__c,center_console_url__c,front_seat_url__c,switch1_url__c,switch2_url__c,other_url_01__c,other_url_02__c,other_url_03__c,other_url_04__c,other_url_05__c,other_url_06__c,other_url_07__c,other_url_08__c,other_url_09__c,other_url_10__c,other_url_11__c,other_url_12__c,other_url_13__c,other_url_14__c,other_url_15__c,other_url_16__c,other_url_17__c,other_url_18__c,other_url_19__c,other_url_20__c,other_url_21__c,other_url_22__c,other_url_23__c,other_url_24__c,other_url_25__c,other_url_26__c,other_url_27__c,other_url_28__c,other_url_29__c,other_url_30__c,other_url_31__c,other_url_32__c,other_url_33__c,other_url_34__c,other_url_35__c,other_url_36__c,other_url_37__c,other_url_38__c,other_url_39__c,other_url_40__c,shakensho_url__c';

        String objectName = 'Assessment__c';
        String recordId = testAssessment.Id;

        for(Integer i = 0; i < imageColumnList.split(',').size(); i++){
            String key = imageColumnList_loop.split(',')[i].trim();
            String value = 'https://'+key;
            testAssessment.put(key,value);
        }
        update testAssessment;
        try {
            Map<String, String> result = AssessPictureController.LoadRecord(imageColumnList, objectName, recordId);
            //必ずエラーになる
            System.assertEquals(0, 1, '例外になりませんでした。');
        }catch (Exception ex){
            System.assertEquals('No such column \'errortest__c\' on entity \'Assessment__c\'. If you are attempting to use a custom field, be sure to append the \'__c\' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.', ex.getMessage(),'エラーが正しくありません');
        }
    }

    //取引先査定表で画像項目すべてセット
    @isTest
    static void testLoadRecordAccountAssessment_SetAllImage() {
        
        //取引先査定表テストデータの作成
        AccountAssessment__c testAccountAssessment = new AccountAssessment__c(asses_tanto__c = getAssesTanto('2'), asset_mngno__c = '20241102_230000_001001');
        insert testAccountAssessment;

        String imageColumnList = 'front_url__c,right_front_url__c,left_front_url__c,left_back_url__c,right_back_url__c,room_url__c,engine_url__c,cotion_url__c,key_url__c,meter_url__c,steering_url__c,center_console_url__c,front_seat_url__c,switch1_url__c,switch2_url__c,other_url_01__c,other_url_02__c,other_url_03__c,other_url_04__c,other_url_05__c,other_url_06__c,other_url_07__c,other_url_08__c,other_url_09__c,other_url_10__c,other_url_11__c,other_url_12__c,other_url_13__c,other_url_14__c,other_url_15__c,other_url_16__c,other_url_17__c,other_url_18__c,other_url_19__c,other_url_20__c,other_url_21__c,other_url_22__c,other_url_23__c,other_url_24__c,other_url_25__c,other_url_26__c,other_url_27__c,other_url_28__c,other_url_29__c,other_url_30__c,other_url_31__c,other_url_32__c,other_url_33__c,other_url_34__c,other_url_35__c,other_url_36__c,other_url_37__c,other_url_38__c,other_url_39__c,other_url_40__c,shakensho_url__c';
        String objectName = 'AccountAssessment__c';
        String recordId = testAccountAssessment.Id;

        for(Integer i = 0; i < imageColumnList.split(',').size(); i++){
            String key = imageColumnList.split(',')[i].trim();
            String value = 'https://'+key;
            testAccountAssessment.put(key,value);
        }
        update testAccountAssessment;

        Map<String, String> result = AssessPictureController.LoadRecord(imageColumnList, objectName, recordId);

        for(String col : imageColumnList.split(',')){
            String imageColum= col.trim();
            System.assertEquals('https://'+imageColum, result.get(imageColum), imageColum+'で期待される画像URLが一致しません。');
        }
    }

    //取引先査定表で画像項目がすべて空
    @isTest
    static void testLoadRecordAccountAssessment_SetNoImage() {
        
        //取引先査定表テストデータの作成
        Id tanto = getAssesTanto('2');
        System.debug(tanto);
        AccountAssessment__c testAccountAssessment = new AccountAssessment__c(asses_tanto__c = getAssesTanto('2'), asset_mngno__c = '20241102_230000_001002');
        insert testAccountAssessment;

        String imageColumnList = 'front_url__c,right_front_url__c,left_front_url__c,left_back_url__c,right_back_url__c,room_url__c,engine_url__c,cotion_url__c,key_url__c,meter_url__c,steering_url__c,center_console_url__c,front_seat_url__c,switch1_url__c,switch2_url__c,other_url_01__c,other_url_02__c,other_url_03__c,other_url_04__c,other_url_05__c,other_url_06__c,other_url_07__c,other_url_08__c,other_url_09__c,other_url_10__c,other_url_11__c,other_url_12__c,other_url_13__c,other_url_14__c,other_url_15__c,other_url_16__c,other_url_17__c,other_url_18__c,other_url_19__c,other_url_20__c,other_url_21__c,other_url_22__c,other_url_23__c,other_url_24__c,other_url_25__c,other_url_26__c,other_url_27__c,other_url_28__c,other_url_29__c,other_url_30__c,other_url_31__c,other_url_32__c,other_url_33__c,other_url_34__c,other_url_35__c,other_url_36__c,other_url_37__c,other_url_38__c,other_url_39__c,other_url_40__c,shakensho_url__c';
        String objectName = 'AccountAssessment__c';
        String recordId = testAccountAssessment.Id;

        Map<String, String> result = AssessPictureController.LoadRecord(imageColumnList, objectName, recordId);

        for(String col : imageColumnList.split(',')){
            String imageColum= col.trim();
            System.assertEquals(null, result.get(imageColum), imageColum+'で期待される画像URLが一致しません。');
        }
    }

    //取引先査定表で画像項目が一部設定、一部空
    @isTest
    static void testLoadRecordAccountAssessment_SetSomeImage() {

        //取引先査定表テストデータの作成
        AccountAssessment__c testAccountAssessment = new AccountAssessment__c(asses_tanto__c = getAssesTanto('2'), asset_mngno__c = '20241102_230000_001003');
        insert testAccountAssessment;

        String imageColumnList = 'front_url__c,right_front_url__c,left_front_url__c,left_back_url__c,right_back_url__c,room_url__c,engine_url__c,cotion_url__c,key_url__c,meter_url__c,steering_url__c,center_console_url__c,front_seat_url__c,switch1_url__c,switch2_url__c,other_url_01__c,other_url_02__c,other_url_03__c,other_url_04__c,other_url_05__c,other_url_06__c,other_url_07__c,other_url_08__c,other_url_09__c,other_url_10__c,other_url_11__c,other_url_12__c,other_url_13__c,other_url_14__c,other_url_15__c,other_url_16__c,other_url_17__c,other_url_18__c,other_url_19__c,other_url_20__c,other_url_21__c,other_url_22__c,other_url_23__c,other_url_24__c,other_url_25__c,other_url_26__c,other_url_27__c,other_url_28__c,other_url_29__c,other_url_30__c,other_url_31__c,other_url_32__c,other_url_33__c,other_url_34__c,other_url_35__c,other_url_36__c,other_url_37__c,other_url_38__c,other_url_39__c,other_url_40__c,shakensho_url__c';
        String objectName = 'AccountAssessment__c';
        String recordId = testAccountAssessment.Id;

        for(Integer i = 0; i < imageColumnList.split(',').size(); i++){
            String key = imageColumnList.split(',')[i].trim();
            String value = '';
            //正面、その他１のみ画像URLをセット
            if(key == 'right_front_url__c' || key == 'other_url_2__c'){
                value ='https://'+key;
            }else{
                value ='';
            }
            testAccountAssessment.put(key,value);
        }
        update testAccountAssessment;

        Map<String, String> result = AssessPictureController.LoadRecord(imageColumnList, objectName, recordId);

        for(String col : imageColumnList.split(',')){
            String imageColum= col.trim();
            if(imageColum == 'right_front_url__c' || imageColum == 'other_url_2__c'){
                System.assertEquals('https://'+imageColum, result.get(imageColum), imageColum+'で期待される画像URLが一致しません。');
            }else{
                System.assertEquals(null, result.get(imageColum), imageColum+'で期待される画像URLが一致しません。');
            }
        }
    }

    //取引先査定表で存在しない項目名の値セット（エラー確認用）
    @isTest
    static void testLoadRecordAccountAssessment_InvalidColumn() {

        //取引先査定表テストデータの作成
        AccountAssessment__c testAccountAssessment = new AccountAssessment__c(asses_tanto__c = getAssesTanto('2'), asset_mngno__c = '20241102_230000_001004');
        insert testAccountAssessment;

        //SFプロパティに「正面」項目なし（代わりにアプリに存在しない項目あり）
        String imageColumnList = 'errortest__c,right_front_url__c,left_front_url__c,left_back_url__c,right_back_url__c,room_url__c,engine_url__c,cotion_url__c,key_url__c,meter_url__c,steering_url__c,center_console_url__c,front_seat_url__c,switch1_url__c,switch2_url__c,other_url_01__c,other_url_02__c,other_url_03__c,other_url_04__c,other_url_05__c,other_url_06__c,other_url_07__c,other_url_08__c,other_url_09__c,other_url_10__c,other_url_11__c,other_url_12__c,other_url_13__c,other_url_14__c,other_url_15__c,other_url_16__c,other_url_17__c,other_url_18__c,other_url_19__c,other_url_20__c,other_url_21__c,other_url_22__c,other_url_23__c,other_url_24__c,other_url_25__c,other_url_26__c,other_url_27__c,other_url_28__c,other_url_29__c,other_url_30__c,other_url_31__c,other_url_32__c,other_url_33__c,other_url_34__c,other_url_35__c,other_url_36__c,other_url_37__c,other_url_38__c,other_url_39__c,other_url_40__c,shakensho_url__c';
        String imageColumnList_loop = 'front_url__c,right_front_url__c,left_front_url__c,left_back_url__c,right_back_url__c,room_url__c,engine_url__c,cotion_url__c,key_url__c,meter_url__c,steering_url__c,center_console_url__c,front_seat_url__c,switch1_url__c,switch2_url__c,other_url_01__c,other_url_02__c,other_url_03__c,other_url_04__c,other_url_05__c,other_url_06__c,other_url_07__c,other_url_08__c,other_url_09__c,other_url_10__c,other_url_11__c,other_url_12__c,other_url_13__c,other_url_14__c,other_url_15__c,other_url_16__c,other_url_17__c,other_url_18__c,other_url_19__c,other_url_20__c,other_url_21__c,other_url_22__c,other_url_23__c,other_url_24__c,other_url_25__c,other_url_26__c,other_url_27__c,other_url_28__c,other_url_29__c,other_url_30__c,other_url_31__c,other_url_32__c,other_url_33__c,other_url_34__c,other_url_35__c,other_url_36__c,other_url_37__c,other_url_38__c,other_url_39__c,other_url_40__c,shakensho_url__c';

        String objectName = 'AccountAssessment__c';
        String recordId = testAccountAssessment.Id;

        for(Integer i = 0; i < imageColumnList.split(',').size(); i++){
            String key = imageColumnList_loop.split(',')[i].trim();
            String value = 'https://'+key; 
            testAccountAssessment.put(key,value);
        }
        update testAccountAssessment;
        try {
            Map<String, String> result = AssessPictureController.LoadRecord(imageColumnList, objectName, recordId);
            //必ずエラーになる
            System.assertEquals(0, 1, '例外になりませんでした。');
        }catch (Exception ex){
            System.assertEquals('No such column \'errortest__c\' on entity \'AccountAssessment__c\'. If you are attempting to use a custom field, be sure to append the \'__c\' after the custom field name. Please reference your WSDL or the describe call for the appropriate names.', ex.getMessage(),'エラーが正しくありません');
        }
    }
}