force-app/main/default/objects/CallCenterA_Opportunity__c/CallCenterA_Opportunity__c.object-meta.xml
<CustomObject>
    <label>コールA商談</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>コールA商談No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/CallCenterA_Opportunity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>コールA商談</relationshipLabel>
    <relationshipName>AccountCallA_Opportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CallCenterA_Opportunity__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>買取受付</label>
    <referenceTo>Case__c</referenceTo>
    <relationshipLabel>コールA商談</relationshipLabel>
    <relationshipName>Case_CallAOpportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/CallCenterA_Opportunity__c/fields/LocationAddress_hs__c.field-meta.xml
<CustomField>
    <fullName>LocationAddress_hs__c</fullName>
    <formula>IF ( SameAsAccountAddress_hs__c = true , Account__r.PersonContact.MailingState &amp; Account__r.PersonContact.MailingCity &amp; Account__r.PersonContact.MailingStreet , Account__r.PersonContact.OtherState &amp; Account__r.PersonContact.OtherCity &amp; Account__r.PersonContact.OtherStreet)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>保管場所住所</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CallCenterA_Opportunity__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>フェーズ</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ア待ち</fullName>
            </value>
            <value>
                <fullName>ア済み</fullName>
            </value>
            <value>
                <fullName>売契待ち</fullName>
            </value>
            <value>
                <fullName>確定待ち</fullName>
            </value>
            <value>
                <fullName>日程調整中</fullName>
            </value>
            <value>
                <fullName>書類待ち</fullName>
            </value>
            <value>
                <fullName>振込待ち</fullName>
            </value>
            <value>
                <fullName>出品待ち</fullName>
            </value>
            <value>
                <fullName>出品中</fullName>
            </value>
            <value>
                <fullName>後処理待ち</fullName>
            </value>
            <value>
                <fullName>全完了</fullName>
            </value>
            <value>
                <fullName>キャンセル</fullName>
            </value>
            <value>
                <fullName>受付</fullName>
                <isActive>false</isActive>
                <label>受付</label>
            </value>
            <value>
                <fullName>買取</fullName>
                <isActive>false</isActive>
                <label>買取</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Case__c/Case__c.object-meta.xml
<CustomObject>
    <label>買取受付</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>買取受付No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Case__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>お名前　★</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>買取受付</relationshipLabel>
    <relationshipName>AccountCase</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/CallAOpportunity__c.field-meta.xml
<CustomField>
    <fullName>CallAOpportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>コールA商談</label>
    <referenceTo>CallCenterA_Opportunity__c</referenceTo>
    <relationshipLabel>買取受付</relationshipLabel>
    <relationshipName>Case_CallAOpportunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <label>グレード</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/LocationAddress_hs__c.field-meta.xml
<CustomField>
    <fullName>LocationAddress_hs__c</fullName>
    <description>個人取引先⇒
　取引先と同じがTRUEの場合は郵送先住所、そうでない場合はその他住所
個人取引先でない⇒
　請求先住所</description>
    <formula>IF( Account__r.IsPerson__c = true , 
 IF( SameAsAccountAddress_hs__c  = true , 
  Account__r.PersonContact.MailingState &amp; Account__r.PersonContact.MailingCity &amp; Account__r.PersonContact.MailingStreet , 
  Account__r.PersonContact.OtherState &amp; Account__r.PersonContact.OtherCity &amp; Account__r.PersonContact.OtherStreet 
 ) , 
 Account__r.BillingState &amp; Account__r.BillingCity &amp; Account__r.BillingStreet
)</formula>
    <label>保管場所住所　★★★</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/Oppotunity__c.field-meta.xml
<CustomField>
    <fullName>Oppotunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>買取商談</label>
    <referenceTo>PurchaseOpportunity__c</referenceTo>
    <relationshipLabel>買取受付</relationshipLabel>
    <relationshipName>OpportunityUnderCustomCase</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Case__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>フェーズ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>受付</fullName>
                <default>true</default>
                <label>受付</label>
            </value>
            <value>
                <fullName>保留</fullName>
            </value>
            <value>
                <fullName>引き継ぎ完了</fullName>
            </value>
            <value>
                <fullName>廃車保留</fullName>
            </value>
            <value>
                <fullName>出品待ち</fullName>
            </value>
            <value>
                <fullName>出品中</fullName>
            </value>
            <value>
                <fullName>商談中</fullName>
            </value>
            <value>
                <fullName>売却</fullName>
            </value>
            <value>
                <fullName>全完了</fullName>
            </value>
            <value>
                <fullName>キャンセル</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PurchaseOpportunity__c/PurchaseOpportunity__c.object-meta.xml
<CustomObject>
    <label>買取商談</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>買取商談No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchaseOpportunity__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>買取商談</relationshipLabel>
    <relationshipName>AccountOpportunity</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunity__c/fields/CancelDate__c.field-meta.xml
<CustomField>
    <fullName>CancelDate__c</fullName>
    <description>フェーズをキャンセルにしたら自動でその日付が入力される</description>
    <inlineHelpText>未入力でフェーズがキャンセルの時、当日が自動的にセットされます。</inlineHelpText>
    <label>キャンセル日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunity__c/fields/Case__c.field-meta.xml
<CustomField>
    <fullName>Case__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>買取受付から買取商談を作成した場合、買取受付Noが表示され作成元の買取受付を確認できる</description>
    <label>買取受付</label>
    <referenceTo>Case__c</referenceTo>
    <relationshipLabel>買取商談</relationshipLabel>
    <relationshipName>CaseUnderOppotunity</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunity__c/fields/CompletionDate__c.field-meta.xml
<CustomField>
    <fullName>CompletionDate__c</fullName>
    <inlineHelpText>未入力でフェーズが全完了の時、当日が自動的にセットされます。</inlineHelpText>
    <label>全完了日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunity__c/fields/Grade__c.field-meta.xml
<CustomField>
    <fullName>Grade__c</fullName>
    <description>過去に使用していたグレード項目、文字列が入力できる形式</description>
    <label>グレード</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunity__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <description>買取商談のフェーズのパスの元になっている項目</description>
    <inlineHelpText>【受付】TEL・FAX等の査定依頼が来た状態。（依頼査定の場合は必ず入力）【保留】査定済み、商談中。未成約状態。（現地で見つけた査定はココからスタート）【買取】成約済み。引取・出品・支払い等進行中【全完了】引取。出品・支払い・後処理等全ての処理が完了【キャンセル】買取できず。</inlineHelpText>
    <label>フェーズ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>受付</fullName>
                <default>true</default>
                <label>受付</label>
            </value>
            <value>
                <fullName>保留</fullName>
            </value>
            <value>
                <fullName>買取</fullName>
            </value>
            <value>
                <fullName>全完了</fullName>
            </value>
            <value>
                <fullName>キャンセル</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/PurchaseOpportunityWork__c/PurchaseOpportunityWork__c.object-meta.xml
<CustomObject>
    <label>買取商談（ワーク）</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>買取商談（ワーク）No.</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/PurchaseOpportunityWork__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>取引先</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>買取商談（ワーク）</relationshipLabel>
    <relationshipName>AccountOpportunityWork</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunityWork__c/fields/CancelDate__c.field-meta.xml
<CustomField>
    <fullName>CancelDate__c</fullName>
    <label>キャンセル日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/PurchaseOpportunityWork__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>フェーズ</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkExchange__c/WorkExchange__c.object-meta.xml
<CustomObject>
    <label>連携用オブジェクト</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>No</label>
        <type>AutoNumber</type>
    </nameField>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WorkExchange__c/fields/CancelDate__c.field-meta.xml
<CustomField>
    <fullName>CancelDate__c</fullName>
    <description>買取受付[CancellationDate__c]</description>
    <label>キャンセル日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WorkExchange__c/fields/CompletionDate__c.field-meta.xml
<CustomField>
    <fullName>CompletionDate__c</fullName>
    <label>全完了日</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/WorkExchange__c/fields/CorporationName__c.field-meta.xml
<CustomField>
    <fullName>CorporationName__c</fullName>
    <label>法人名</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WorkExchange__c/fields/Name_kana__c.field-meta.xml
<CustomField>
    <fullName>Name_kana__c</fullName>
    <label>取引先名＿よみがな</label>
    <length>1024</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/WorkExchange__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>買取受付フェーズ</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>受付</fullName>
            </value>
            <value>
                <fullName>保留</fullName>
            </value>
            <value>
                <fullName>引き継ぎ完了</fullName>
            </value>
            <value>
                <fullName>買取</fullName>
            </value>
            <value>
                <fullName>日程調整</fullName>
            </value>
            <value>
                <fullName>書類待ち</fullName>
            </value>
            <value>
                <fullName>後処理待ち</fullName>
            </value>
            <value>
                <fullName>全完了</fullName>
            </value>
            <value>
                <fullName>キャンセル</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NXI_Dao.cls
public class NXI_Dao {
    //**ユーザ**
    public static List<User> getUsers() {
        String soql = '';
        soql += 'SELECT ';
        soql += NXI_Dao.createSelect('User');
        soql += 'FROM User ';
        return Database.query(soql);
    }
    //**買取受付**
    public static List<Case__c> getCustomCase(List<Id> recordId) {
        String soql = '';
        soql += 'SELECT ';
        soql += NXI_Dao.createSelect('Case__c');
        soql += ', CallAOpportunity__r.Phase__c ';
        soql += ', Oppotunity__r.Phase__c ';
        soql += ', Oppotunity__r.Grade__c ';
        soql += ', CallAOpportunity__r.LocationAddress_hs__c ';
        soql += ', Account__r.LastName ';
        soql += ', Account__r.IsPerson__c ';
        soql += ', Account__r.Name ';
        soql += ', Account__r.Name_kana__c ';
        soql += ', Account__r.Fax ';
        soql += ', Account__r.CorporationName__c ';
        soql += ', Account__r.FirstName ';
        soql += ', Account__r.PersonEmail ';
        soql += ', Account__r.PersonMobilePhone ';
        soql += ', Account__r.PersonOtherCity ';
        soql += ', Account__r.PersonMailingCity ';
        //数式soql += ', Account__r.PersonMailingAddress ';
        soql += ', Account__r.PersonOtherStreet ';
        soql += ', Account__r.PersonMailingStreet ';
        soql += ', Account__r.PersonOtherState ';
        soql += ', Account__r.PersonMailingState ';
        soql += ', Account__r.PersonOtherPostalCode ';
        soql += ', Account__r.PersonMailingPostalCode ';
        soql += ', Oppotunity__r.CreatedDate ';
        soql += ', Oppotunity__r.CompletionDate__c ';
        soql += ', Oppotunity__r.CancelDate__c ';
        soql += ', Oppotunity__r.CancelReason__c ';
        soql += ', Grades__r.Name ';
        
        soql += 'FROM Case__c ';
        soql += 'WHERE Id IN :recordId ';
        return Database.query(soql);
    }
    //**連携テーブル**
    public static List<WorkExchange__c> getWorkExchange(List<Id> recordId) {
        String soql = '';
        soql += 'SELECT ';
        soql += NXI_Dao.createSelect('WorkExchange__c');
        soql += 'FROM WorkExchange__c ';
        soql += 'WHERE Id IN :recordId ';
        return Database.query(soql);
    }
    /*
     //**買取商談**
    public static List<PurchaseOpportunity__c> getPurchaseOpportunity(List<Id> recordId) {
        String soql = '';
        soql += 'SELECT ';
        soql += NXI_Dao.createSelect('PurchaseOpportunity__c');
        soql += 'FROM PurchaseOpportunity__c ';
        soql += 'WHERE Id IN :recordId ';
        return Database.query(soql);
    }
    //**CallA**
    public static List<CallCenterA_Opportunity__c> getCallCenterA_Opportunity(List<Id> recordId) {
        String soql = '';
        soql += 'SELECT ';
        soql += NXI_Dao.createSelect('CallCenterA_Opportunity__c');
        soql += 'FROM CallCenterA_Opportunity__c ';
        soql += 'WHERE Id IN :recordId ';
        return Database.query(soql);
    }
     //**Account**
    public static List<Account> getAccount(List<Id> recordId) {
        String soql = '';
        soql += 'SELECT ';
        soql += NXI_Dao.createSelect('Account');
        soql += 'FROM Account ';
        soql += 'WHERE Id IN :recordId ';
        return Database.query(soql);
    }
    //**User**
    public static List<User> getUser(List<String> UserCode) {
        String soql = '';
        soql += 'SELECT ';
        soql += NXI_Dao.createSelect('User');
        soql += 'FROM User ';
        soql += 'WHERE UserCode__c  IN :UserCode ';
        return Database.query(soql);
    }*/
    
    //**買取商談（ワーク）**
    public static List<PurchaseOpportunityWork__c> getPurchaseOpportunityWorks(List<PurchaseOpportunityWork__c> pOpportunityWorks) {
        String soql = '';
        soql += 'SELECT ';
        soql += NXI_Dao.createSelect('PurchaseOpportunityWork__c');
        soql += 'FROM PurchaseOpportunityWork__c ';
        soql += 'WHERE Id IN :pOpportunityWorks ';
        return Database.query(soql);
    }
    
    //**買取実績（ワーク）**
    public static List<PurchaseExperienceWork__c> getPurchaseExperienceWorks(List<PurchaseExperienceWork__c> pExperienceWorks) {
        String soql = '';
        soql += 'SELECT ';
        soql += NXI_Dao.createSelect('PurchaseExperienceWork__c');
        soql += 'FROM PurchaseExperienceWork__c ';
        soql += 'WHERE Id IN :pExperienceWorks ';
        return Database.query(soql);
    }

    //買取商談の直近査定日を取引先ごとに取得
    public static String getLastAssessmentDateByAccount() {
        String soql = '';
        soql += 'SELECT ';
        soql += 'Account__c ';
        soql += ', MAX(AssessmentDate__c) LastAssessmentDate ';
        soql += ', MAX(PurchaseDate__c) LastPurchaseDate ';
        soql += 'FROM PurchaseOpportunity__c ';
        soql += 'WHERE AggregationDate__c = LAST_N_DAYS:80 ';
        soql += 'GROUP BY Account__c ';
        soql += 'LIMIT 50000 ';
        
        return soql;
    }
    
    //**ヘルパー**
    //オブジェクトの全項目を取得するSELECT句を作成
    public static String createSelect(String objectName) {
        Schema.SObjectType sType = (Schema.SObjectType)Schema.getGlobalDescribe().get(objectName);
        Schema.DescribeSObjectResult sObjectResult = sType.getDescribe();
        Map<String, Schema.SObjectField> fieldMap = sObjectResult.fields.getMap();
        
        String selectFields = '';
        for (Schema.SObjectField field : fieldMap.values()) {
            if (selectFields.length() > 0) {
                selectFields = selectFields + ', ';
            }
            Schema.DescribeFieldResult fieldResult = field.getDescribe();
            selectFields = selectFields + fieldResult.getName();
        }
        return selectFields + ' ';
    }
    /*
     //オブジェクトの書き込み可能な項目を取得するSELECT句を作成
    public static String createSelectWritable(String objectName) {
        Schema.SObjectType sType = (Schema.SObjectType)Schema.getGlobalDescribe().get(objectName);
        Schema.DescribeSObjectResult sObjectResult = sType.getDescribe();
        Map<String, Schema.SObjectField> fieldMap = sObjectResult.fields.getMap();
        
        String selectFields = '';
        for (Schema.SObjectField field : fieldMap.values()) {           

            if (selectFields.length() > 0) {
                selectFields = selectFields + ', ';
            }
            Schema.DescribeFieldResult fieldResult = field.getDescribe();
            if(!fieldResult.isCreateable()){
                continue;
            }
            selectFields = selectFields + fieldResult.getName();
        }
        return selectFields + ' ';
    }*/
}